In [1]:

import pandas as pd
import numpy as np
%pip install openpyxl
sale = pd.read_csv("sale.csv")
purchase = pd.read_csv("purchase.csv")
inventory = pd.read_csv("inventory.csv")
print(sale.columns)
print(purchase.columns)
print(inventory.columns)

Requirement already satisfied: openpyxl in ./.venv/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.
Index(['Branch', 'Date', 'Time', 'Slip ID', 'Slip Number', 'Line No',
       'Line ID', 'Stock Code', 'Description', 'Selling Price', 'Qty', 'UOM',
       'Discount Amount', 'Amount', 'Net Amount', 'Location', 'Buying Price',
       'Profit', 'Profit Margin %'],
      dtype='str')
Index(['Branch', 'Date', 'Stock Code', 'Description', 'Quantity', 'UOM',
       'Buying Price', 'Location'],
      dtype='str')
Index(['Branch', 'Last Updated', 'Stock Code', 'Description', 'Group',
       'On Hand Qty', 'Buying Price', 'Selling Price', 'Location'],
      dtype='str')

Step1 - Data parparation 
Original data
   ↓
Clean Branch names
   ↓
Keep only Ashley
   ↓
Convert dates
   ↓
Clean stock codes
   ↓
Clean descriptions
   ↓
Convert numbers
   ↓
Check rows
   ↓
Check date ranges
   ↓
Check missing values
   ↓
Check data types
   ↓
Preview cleaned Ashley data

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# ASHLEY BRANCH - DATA PREPARATION
# =========================================================
# STEP 1 - LOAD DATA
# =========================================================

# Change these to your actual file names

sale = pd.read_csv("sale.csv")
purchase = pd.read_csv("purchase.csv")
inventory = pd.read_csv("inventory.csv")


# STEP 2 - CLEAN COLUMN NAMES
# =========================================================

sale.columns = sale.columns.str.strip()
purchase.columns = purchase.columns.str.strip()
inventory.columns = inventory.columns.str.strip()



# =========================================================
# STEP 3 - CLEAN BRANCH NAMES
# =========================================================

for data in [sale, purchase, inventory]:

    data["Branch"] = (
        data["Branch"]
        .astype(str)
        .str.strip()
    )


# =========================================================
# STEP 4 - KEEP ONLY ASHLEY BRANCH
# =========================================================

sale = sale[
    sale["Branch"].str.lower() == "ashley"
].copy()

purchase = purchase[
    purchase["Branch"].str.lower() == "ashley"
].copy()

inventory = inventory[
    inventory["Branch"].str.lower() == "ashley"
].copy()




print("Ashley branch selected")

print("Sale rows:", len(sale))
print("Purchase rows:", len(purchase))
print("Inventory rows:", len(inventory))



# =========================================================
# STEP 5 - CONVERT DATES
# =========================================================

sale["Date"] = pd.to_datetime(
    sale["Date"],
    errors="coerce"
)

purchase["Date"] = pd.to_datetime(
    purchase["Date"],
    errors="coerce"
)

inventory["Last Updated"] = pd.to_datetime(
    inventory["Last Updated"],
    errors="coerce"
)



# =========================================================
# STEP 6 - CLEAN STOCK CODES
# =========================================================

for data in [sale, purchase, inventory]:

    data["Stock Code"] = (
        data["Stock Code"]
        .astype(str)
        .str.strip()
        .str.upper()
    )


# =========================================================
# STEP 7 - CLEAN DESCRIPTION
# =========================================================

for data in [sale, purchase, inventory]:

    if "Description" in data.columns:

        data["Description"] = (
            data["Description"]
            .astype(str)
            .str.strip()
        )


# =========================================================
# STEP 8 - CONVERT SALE NUMBERS
# =========================================================

sale_numeric = [
    "Selling Price",
    "Qty",
    "Net Amount",
    "Buying Price",
    "Profit",
    "Profit Margin %"
]

for col in sale_numeric:

    if col in sale.columns:

        sale[col] = pd.to_numeric(
            sale[col],
            errors="coerce"
        )


# =========================================================
# STEP 9 - CONVERT PURCHASE NUMBERS
# =========================================================

purchase_numeric = [
    "Quantity",
    "Buying Price"
]

for col in purchase_numeric:

    if col in purchase.columns:

        purchase[col] = pd.to_numeric(
            purchase[col],
            errors="coerce"
        )


# =========================================================
# STEP 10 - CONVERT INVENTORY NUMBERS
# =========================================================

inventory_numeric = [
    "On Hand Qty",
    "Buying Price",
    "Selling Price"
]

for col in inventory_numeric:

    if col in inventory.columns:

        inventory[col] = pd.to_numeric(
            inventory[col],
            errors="coerce"
        )


# =========================================================
# STEP 11 - DATE RANGE
# =========================================================

print("\n========== DATE RANGE ==========")

print("\nSALE")
print("Start:", sale["Date"].min())
print("End:", sale["Date"].max())

print("\nPURCHASE")
print("Start:", purchase["Date"].min())
print("End:", purchase["Date"].max())

print("\nINVENTORY")
print("Start:", inventory["Last Updated"].min())
print("End:", inventory["Last Updated"].max())


# =========================================================
# STEP 12 - MISSING VALUES
# =========================================================

print("\n========== MISSING VALUES ==========")

print("\nSALE")
print(
    sale[
        ["Date", "Stock Code", "Qty", "Net Amount"]
    ].isna().sum()
)

print("\nPURCHASE")
print(
    purchase[
        ["Date", "Stock Code", "Quantity", "Buying Price"]
    ].isna().sum()
)

print("\nINVENTORY")
print(
    inventory[
        ["Last Updated", "Stock Code", "On Hand Qty"]
    ].isna().sum()
)


# =========================================================
# STEP 13 - CHECK DATA TYPES
# =========================================================

print("\n========== DATA TYPES ==========")

print("\nSALE")
print(sale.dtypes)

print("\nPURCHASE")
print(purchase.dtypes)

print("\nINVENTORY")
print(inventory.dtypes)


# =========================================================
# STEP 14 - PREVIEW DATA
# =========================================================

print("\n========== SALE SAMPLE ==========")

print(
    sale[
        [
            "Date",
            "Stock Code",
            "Description",
            "Qty",
            "Selling Price",
            "Buying Price",
            "Profit"
        ]
    ].head()
)


print("\n========== PURCHASE SAMPLE ==========")

print(
    purchase[
        [
            "Date",
            "Stock Code",
            "Description",
            "Quantity",
            "Buying Price"
        ]
    ].head()
)


print("\n========== INVENTORY SAMPLE ==========")

print(
    inventory[
        [
            "Last Updated",
            "Stock Code",
            "Description",
            "Group",
            "On Hand Qty",
            "Buying Price",
            "Selling Price"
        ]
    ].head()
)


print("\n====================================")
print("ASHLEY DATA PREPARATION COMPLETE")
print("====================================")

Ashley branch selected
Sale rows: 9459
Purchase rows: 15
Inventory rows: 643

========== DATE RANGE ==========

SALE
Start: 2025-02-09 00:00:00
End: 2026-09-04 00:00:00

PURCHASE
Start: 2026-09-04 00:00:00
End: 2026-09-04 00:00:00

INVENTORY
Start: 2026-09-04 19:17:32
End: 2026-09-04 19:17:32

========== MISSING VALUES ==========

SALE
Date          0
Stock Code    0
Qty           0
Net Amount    0
dtype: int64

PURCHASE
Date            0
Stock Code      0
Quantity        0
Buying Price    0
dtype: int64

INVENTORY
Last Updated    0
Stock Code      0
On Hand Qty     0
dtype: int64

========== DATA TYPES ==========

SALE
Branch                        str
Date               datetime64[us]
Time                          str
Slip ID                       str
Slip Number                 int64
Line No                     int64
Line ID                       str
Stock Code                    str
Description                   str
Selling Price             float64
Qty                       float64
UOM                           str
Discount Amount           float64
Amount                    float64
Net Amount                float64
Location                      str
Buying Price              float64
Profit                    float64
Profit Margin %           float64
dtype: object

PURCHASE
Branch                     str
Date            datetime64[us]
Stock Code                 str
Description                str
Quantity               float64
UOM                        str
Buying Price           float64
Location                   str
dtype: object

INVENTORY
Branch                      str
Last Updated     datetime64[us]
Stock Code                  str
Description                 str
Group                       str
On Hand Qty             float64
Buying Price            float64
Selling Price           float64
Location                    str
dtype: object

========== SALE SAMPLE ==========
          Date  Stock Code  Description  Qty  Selling Price  Buying Price  \
92  2026-09-04       71641         Smil  1.0        15500.0       11500.0
93  2026-09-04  SNS788001A  Shwenannsan  1.0        12500.0        8800.0
96  2026-09-04    E7164B71        Luofu  1.0        32000.0       22700.0
98  2026-09-04    E6217E38        Luofu  1.0        42500.0       31000.0
100 2026-09-04       E6217        Luofu  1.0        41500.0       31000.0

      Profit
92    4000.0
93    3700.0
96    9300.0
98   11500.0
100  10500.0

========== PURCHASE SAMPLE ==========
        Date Stock Code Description  Quantity  Buying Price
0 2026-09-04     SPX007       Lolla       3.0       17650.0
1 2026-09-04     SPX002       Lolla       4.0       17800.0
2 2026-09-04     F27005     Maldini       6.0       32150.0
3 2026-09-04     MN8231     Maldini       6.0       27550.0
4 2026-09-04    AM19217     Maldini       6.0       28200.0

========== INVENTORY SAMPLE ==========
         Last Updated Stock Code Description  Group  On Hand Qty  \
0 2026-09-04 19:17:32     000025     မိုးစီး   Lady          1.0
1 2026-09-04 19:17:32     000127       Nilin   Lady          1.0
2 2026-09-04 19:17:32     000139     ဆင်ကြယ်    Men         56.0
3 2026-09-04 19:17:32     000140      Shower    Men          8.0
4 2026-09-04 19:17:32      01514  Male Shoes  Child          5.0

   Buying Price  Selling Price
0      15050.00        24500.0
1      16940.00        27200.0
2      18581.66        21000.0
3       4900.00        12000.0
4      16800.00        23500.0

====================================
ASHLEY DATA PREPARATION COMPLETE
====================================

In [3]:
# ==========================================
# ASHLEY - COMPLETE MISSING VALUE CHECK
# ==========================================

print("========== SALE ==========")
print("Total rows:", len(sale))
print("\nMissing values by column:")
print(sale.isna().sum())


print("\n========== PURCHASE ==========")
print("Total rows:", len(purchase))
print("\nMissing values by column:")
print(purchase.isna().sum())


print("\n========== INVENTORY ==========")
print("Total rows:", len(inventory))
print("\nMissing values by column:")
print(inventory.isna().sum())

========== SALE ==========
Total rows: 9459

Missing values by column:
Branch                0
Date                  0
Time                  0
Slip ID               0
Slip Number           0
Line No               0
Line ID               0
Stock Code            0
Description           3
Selling Price         0
Qty                   0
UOM                   0
Discount Amount       0
Amount                0
Net Amount            0
Location              0
Buying Price       7981
Profit             7981
Profit Margin %    7981
dtype: int64

========== PURCHASE ==========
Total rows: 15

Missing values by column:
Branch          0
Date            0
Stock Code      0
Description     0
Quantity        0
UOM             0
Buying Price    0
Location        0
dtype: int64

========== INVENTORY ==========
Total rows: 643

Missing values by column:
Branch           0
Last Updated     0
Stock Code       0
Description      1
Group            1
On Hand Qty      0
Buying Price     0
Selling Price    0
Location         0
dtype: int64

In [4]:
import pandas as pd

sale["Date"] = pd.to_datetime(sale["Date"])

sale.sort_values(by="Date", ascending=True).head(10)

,Branch,Date,Time,Slip ID,Slip Number,Line No,Line ID,Stock Code,Description,Selling Price,Qty,UOM,Discount Amount,Amount,Net Amount,Location,Buying Price,Profit,Profit Margin %
16223,Ashley,2025-02-09,12:39:14,20250209-001,1,25,20250209-001-25,WR1102,Gooddy,16900.0,2.0,Each,0.0,33800.0,33800.0,Ashley,NaN,NaN,NaN
16199,Ashley,2025-02-09,12:39:14,20250209-001,1,1,20250209-001-01,60892,Member's Menu,7400.0,1.0,Each,0.0,7400.0,7400.0,Ashley,NaN,NaN,NaN
16200,Ashley,2025-02-09,12:39:14,20250209-001,1,2,20250209-001-02,KML645,Khaing Marlar,22500.0,1.0,Each,0.0,22500.0,22500.0,Ashley,NaN,NaN,NaN
16201,Ashley,2025-02-09,12:39:14,20250209-001,1,3,20250209-001-03,000141,Fashion,10500.0,1.0,Each,0.0,10500.0,10500.0,Ashley,NaN,NaN,NaN
16202,Ashley,2025-02-09,12:39:14,20250209-001,1,4,20250209-001-04,300038,Chanel,7500.0,2.0,Each,0.0,15000.0,15000.0,Ashley,NaN,NaN,NaN
16203,Ashley,2025-02-09,12:39:14,20250209-001,1,5,20250209-001-05,B2802,Marina,16700.0,2.0,Each,0.0,33400.0,33400.0,Ashley,NaN,NaN,NaN
16204,Ashley,2025-02-09,12:39:14,20250209-001,1,6,20250209-001-06,B04489,Govy Soft,19500.0,1.0,Each,0.0,19500.0,19500.0,Ashley,NaN,NaN,NaN
16205,Ashley,2025-02-09,12:39:14,20250209-001,1,7,20250209-001-07,TK12030,Thit Khaw,14400.0,1.0,Each,0.0,14400.0,14400.0,Ashley,NaN,NaN,NaN
16206,Ashley,2025-02-09,12:39:14,20250209-001,1,8,20250209-001-08,K275800A,ခန့်ခန့်လေး,8200.0,1.0,Each,0.0,8200.0,8200.0,Ashley,NaN,NaN,NaN
16207,Ashley,2025-02-09,12:39:14,20250209-001,1,9,20250209-001-09,K273000A,K2,4200.0,2.0,Each,0.0,8400.0,8400.0,Ashley,NaN,NaN,NaN

In [5]:
# =========================================================
# STEP 2A - CHECK PRODUCT COVERAGE
# =========================================================

print("========== PRODUCT COUNTS ==========")

print(
    "Unique products in SALE:",
    sale["Stock Code"].nunique()
)

print(
    "Unique products in INVENTORY:",
    inventory["Stock Code"].nunique()
)

print(
    "Unique products in PURCHASE:",
    purchase["Stock Code"].nunique()
)


# =========================================================
# PRODUCTS IN SALE BUT NOT INVENTORY
# =========================================================

sale_codes = set(sale["Stock Code"])

inventory_codes = set(inventory["Stock Code"])

purchase_codes = set(purchase["Stock Code"])


sale_not_inventory = sale_codes - inventory_codes

print("\n========== SALE BUT NOT INVENTORY ==========")

print("Number of products:", len(sale_not_inventory))

print("Sample:")
print(list(sale_not_inventory)[:20])


# =========================================================
# PRODUCTS IN INVENTORY BUT NEVER APPEAR IN SALE
# =========================================================

inventory_not_sale = inventory_codes - sale_codes

print("\n========== INVENTORY BUT NOT SALE ==========")

print("Number of products:", len(inventory_not_sale))

print("Sample:")
print(list(inventory_not_sale)[:20])


# =========================================================
# PRODUCTS APPEARING IN BOTH
# =========================================================

sale_inventory_match = sale_codes & inventory_codes

print("\n========== SALE + INVENTORY MATCH ==========")

print(
    "Number of matching products:",
    len(sale_inventory_match)
)

========== PRODUCT COUNTS ==========
Unique products in SALE: 1196
Unique products in INVENTORY: 643
Unique products in PURCHASE: 15

========== SALE BUT NOT INVENTORY ==========
Number of products: 677
Sample:
['YB1', 'AB620W', 'SNS6700', 'TA011', 'A01585', 'TK8000', 'JASF01', 'A00492', 'MF015', 'SNS5000', '1127', 'A01616', 'F26', '000075', 'A00096', 'MC15', 'NO8041', 'SNS4400', 'E7158', '000020']

========== INVENTORY BUT NOT SALE ==========
Number of products: 124
Sample:
['VT66', '2222', 'MC01-41', 'SNS78800A', '88813', 'JB025', 'VR05', '80828', 'FPU330155PC', 'DD4203-39', 'JJ5115-37', 'DD4203-36', 'MC01-42-43', 'LL5480', 'JB014', '205S', 'HELLODAY', 'AO903', 'JB026', 'A9684']

========== SALE + INVENTORY MATCH ==========
Number of matching products: 519

Step2 - Create a Product Master. Build one row per Stock Code containing fields such as Description, Group/Category, current Selling Price, current Buying Price, and current On Hand Qty. This becomes the main reference table for every later layer.

In [6]:
# =========================================================
# STEP 2 - CREATE PRODUCT MASTER
# ASHLEY BRANCH ONLY
# =========================================================


# ---------------------------------------------------------
# 2.0 FILTER ALL DATA TO ASHLEY ONLY
# ---------------------------------------------------------

sale = sale[
    sale["Branch"].astype(str).str.strip().str.lower() == "ashley"
].copy()

purchase = purchase[
    purchase["Branch"].astype(str).str.strip().str.lower() == "ashley"
].copy()

inventory = inventory[
    inventory["Branch"].astype(str).str.strip().str.lower() == "ashley"
].copy()


# Check branch before continuing
print("========== ASHLEY FILTER CHECK ==========")

print("Sale branches:")
print(sale["Branch"].value_counts())

print("\nPurchase branches:")
print(purchase["Branch"].value_counts())

print("\nInventory branches:")
print(inventory["Branch"].value_counts())


# ---------------------------------------------------------
# 2.1 CREATE LIST OF EVERY PRODUCT
# ---------------------------------------------------------

all_codes = (
    set(sale["Stock Code"])
    | set(inventory["Stock Code"])
    | set(purchase["Stock Code"])
)

product_master = pd.DataFrame({
    "Stock Code": sorted(all_codes)
})

# Add Branch
product_master["Branch"] = "Ashley"


# ---------------------------------------------------------
# 2.2 PREPARE INVENTORY INFORMATION
# ---------------------------------------------------------

inventory_info = (
    inventory[
        [
            "Stock Code",
            "Description",
            "Group",
            "Selling Price",
            "Buying Price",
            "On Hand Qty"
        ]
    ]
    .drop_duplicates(
        subset="Stock Code",
        keep="last"
    )
)

inventory_info = inventory_info.rename(
    columns={
        "Description": "Description_Inventory"
    }
)


# ---------------------------------------------------------
# 2.3 PREPARE SALE INFORMATION
# ---------------------------------------------------------

# SALE does NOT contain Group
# so we use only Stock Code + Description here

sale_info = (
    sale[
        [
            "Stock Code",
            "Description"
        ]
    ]
    .drop_duplicates(
        subset="Stock Code",
        keep="last"
    )
)

sale_info = sale_info.rename(
    columns={
        "Description": "Description_Sale"
    }
)


# ---------------------------------------------------------
# 2.4 MERGE INVENTORY INFORMATION
# ---------------------------------------------------------

product_master = product_master.merge(
    inventory_info,
    on="Stock Code",
    how="left"
)


# ---------------------------------------------------------
# 2.5 MERGE SALE INFORMATION
# ---------------------------------------------------------

product_master = product_master.merge(
    sale_info,
    on="Stock Code",
    how="left"
)


# ---------------------------------------------------------
# 2.6 CREATE FINAL DESCRIPTION
# ---------------------------------------------------------

# First use Inventory description.
# If missing, use Sale description.

product_master["Description"] = (
    product_master["Description_Inventory"]
    .fillna(product_master["Description_Sale"])
)


# ---------------------------------------------------------
# 2.7 REMOVE TEMPORARY DESCRIPTION COLUMNS
# ---------------------------------------------------------

product_master = product_master.drop(
    columns=[
        "Description_Inventory",
        "Description_Sale"
    ]
)


# ---------------------------------------------------------
# 2.8 ADD SOURCE FLAGS
# ---------------------------------------------------------

product_master["In Sale"] = (
    product_master["Stock Code"]
    .isin(sale["Stock Code"])
)

product_master["In Inventory"] = (
    product_master["Stock Code"]
    .isin(inventory["Stock Code"])
)

product_master["In Purchase"] = (
    product_master["Stock Code"]
    .isin(purchase["Stock Code"])
)


# ---------------------------------------------------------
# 2.9 REORDER COLUMNS
# ---------------------------------------------------------

product_master = product_master[
    [
        "Branch",
        "Stock Code",
        "Description",
        "Group",
        "Selling Price",
        "Buying Price",
        "On Hand Qty",
        "In Sale",
        "In Inventory",
        "In Purchase"
    ]
]


# ---------------------------------------------------------
# 2.10 CHECK RESULT
# ---------------------------------------------------------

print("\n========== PRODUCT MASTER ==========")

print("\nBranch:")
print(product_master["Branch"].value_counts())

print("\nTotal Products:")
print(len(product_master))

print("\nMissing Values:")
print(product_master.isna().sum())

print("\nSample:")
print(product_master.head(20).to_string(index=False))

========== ASHLEY FILTER CHECK ==========
Sale branches:
Branch
Ashley    9459
Name: count, dtype: int64

Purchase branches:
Branch
Ashley    15
Name: count, dtype: int64

Inventory branches:
Branch
Ashley    643
Name: count, dtype: int64

========== PRODUCT MASTER ==========

Branch:
Branch
Ashley    1320
Name: count, dtype: int64

Total Products:
1320

Missing Values:
Branch             0
Stock Code         0
Description        1
Group            678
Selling Price    677
Buying Price     677
On Hand Qty      677
In Sale            0
In Inventory       0
In Purchase        0
dtype: int64

Sample:
Branch Stock Code Description Group  Selling Price  Buying Price  On Hand Qty  In Sale  In Inventory  In Purchase
Ashley     000001    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000002    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000005    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000006    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000008    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000009    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000011    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000012    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000015    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000016    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000018    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000020    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000021    Aerosoft   NaN            NaN           NaN          NaN     True         False        False
Ashley     000024       Cross   NaN            NaN           NaN          NaN     True         False        False
Ashley     000025     မိုးစီး  Lady        24500.0       15050.0          1.0     True          True        False
Ashley     000026        Immi   NaN            NaN           NaN          NaN     True         False        False
Ashley     000027         Imm   NaN            NaN           NaN          NaN     True         False        False
Ashley     000028    Belongse   NaN            NaN           NaN          NaN     True         False        False
Ashley     000037       Lolla   NaN            NaN           NaN          NaN     True         False        False
Ashley     000038     Limited   NaN            NaN           NaN          NaN     True         False        False

Step2- Missing value preparation. 
2.1- finding the missing value. 
2.2-thinking how to make this missing vlalue ( which part can i use )

2.1 Missing value question-1 
How to solve the missing value errors 1. first thinking “Are the 677 missing products caused by different historical periods?”
How do we solve the missing value problem for the 677 products?
Initial Thinking:
Are the 677 missing products caused by different historical periods?
Step 1 — Check when the missing products were last sold
Result:
- 🟢 535 products were last sold more than 6 months ago.
- 🟡 118 products were last sold 31–180 days ago.
- 🔴 24 products were last sold within the last 30 days.
Finding:
Most missing products are old or inactive products. However, 24 products were sold very recently, so they require further investigation.
Step 2 — Check which data source is missing for the 24 recent products
Result:
- Sales: ✅ Product exists
- Purchase: ❌ Product not found
- Inventory: ❌ Product not found
- Total affected: 24 products
Interpretation:
The 24 products were recently sold but are absent from both the current Purchase dataset and Inventory snapshot.
This does not yet prove that the Purchase or Inventory system is wrong. Possible causes include:
- Historical Purchase data is incomplete.
- The product was purchased before the available Purchase data period.
- Inventory snapshot excludes zero-stock products.
- Stock codes are different between datasets.
- Opening stock, stock transfer, return, or manual adjustment created the inventory.
Recommended Action:
Collect more historical Purchase data and check the 24 products again. Products still unmatched after this check should be treated as data-quality problems.
Step 2 — Check which data source is missing for the 24 recent products
Result:
- Sales: ✅ Product exists
- Purchase: ❌ Product not found in currently available Purchase data
- Inventory: ❌ Product not found in current Inventory snapshot
- Total affected: 24 products
Interpretation:
The 24 products were recently sold but cannot be matched with the currently available Purchase data or current Inventory snapshot. Because the complete historical Purchase data is not yet available, do not classify these as confirmed data errors.
Recommended Action:
🟡 Keep these 24 products as an internal developer warning. Once complete Purchase data becomes available, check them again. If they are still unexplained, escalate them for further data-quality investigation.
File 2 — Change the Alarm Rule
Level	Condition	Meaning	System Action
🟢 Accept	Last sale > 180 days	Likely historical/inactive product	Accept missing current values
🟡 Warning	Last sale 31–180 days	Missing data may require checking	Internal developer warning
🟡 Warning	Last sale ≤30 days + incomplete Purchase history	Recent mismatch, but cause cannot yet be confirmed	Log higher-priority developer warning and recheck when full Purchase data is available
🔴 Alert	Recent product still unexplained after sufficient source data is available	Strong evidence of a real data-quality problem	Investigate immediately


Current logic becomes:
677 Missing Products
        │
        ▼
Check Last Sale Date
        │
   ┌────┼────────────┐
   ▼    ▼            ▼
 ≤30d  31–180d     >180d
  24      118         535
  🟡       🟡          🟢
Warning  Warning     Accept
  │
  ▼
High-priority warning
until full Purchase
history is available
And change the current developer message to:
🟡 Recent Data Mismatch: Product was recently sold but cannot be matched with the currently available Purchase and Inventory data. Complete Purchase history is unavailable. Recheck when sufficient Purchase data becomes available.

The 🔴 alert is therefore reserved for later, when you have sufficient source data and the mismatch still cannot be explained.

In [7]:
# =========================================================
# STEP 2 DIAGNOSTIC ONLY
# CHECK WHEN THE 677 MISSING PRODUCTS WERE LAST SOLD
# DO NOT MODIFY PRODUCT MASTER
# =========================================================

import pandas as pd

# Reference date = Purchase / Inventory snapshot date
reference_date = pd.Timestamp("2026-09-04")

# ---------------------------------------------------------
# 1. Get the 677 Stock Codes
# ---------------------------------------------------------

missing_codes = set(
    product_master.loc[
        product_master["Selling Price"].isna()
        & product_master["Buying Price"].isna()
        & product_master["On Hand Qty"].isna(),
        "Stock Code"
    ]
)

# ---------------------------------------------------------
# 2. Filter Sale data for only those missing products
# ---------------------------------------------------------

missing_sales = sale[
    sale["Stock Code"].isin(missing_codes)
].copy()

missing_sales["Date"] = pd.to_datetime(
    missing_sales["Date"],
    errors="coerce"
)

# ---------------------------------------------------------
# 3. Find First Sale Date and Last Sale Date per product
# ---------------------------------------------------------

missing_product_dates = (
    missing_sales
    .groupby("Stock Code")["Date"]
    .agg(
        First_Sale_Date="min",
        Last_Sale_Date="max"
    )
    .reset_index()
)

# ---------------------------------------------------------
# 4. Calculate Days Since Last Sale
# ---------------------------------------------------------

missing_product_dates["Days_Since_Last_Sale"] = (
    reference_date - missing_product_dates["Last_Sale_Date"]
).dt.days

# ---------------------------------------------------------
# 5. Overall summary
# ---------------------------------------------------------

total_missing = len(missing_product_dates)

earliest_first_sale = missing_product_dates["First_Sale_Date"].min()
latest_last_sale = missing_product_dates["Last_Sale_Date"].max()

# ---------------------------------------------------------
# 6. Count products by how long ago they were last sold
# ---------------------------------------------------------

sold_last_30_days = (
    missing_product_dates["Days_Since_Last_Sale"] <= 30
).sum()

sold_31_90_days = (
    missing_product_dates["Days_Since_Last_Sale"].between(31, 90)
).sum()

sold_91_180_days = (
    missing_product_dates["Days_Since_Last_Sale"].between(91, 180)
).sum()

sold_181_365_days = (
    missing_product_dates["Days_Since_Last_Sale"].between(181, 365)
).sum()

sold_over_365_days = (
    missing_product_dates["Days_Since_Last_Sale"] > 365
).sum()

# ---------------------------------------------------------
# 7. Print simple summary
# ---------------------------------------------------------

print("========== 677 MISSING PRODUCT TIME SUMMARY ==========")

print(f"\nMissing products: {total_missing}")

print(f"\nEarliest first sale: {earliest_first_sale.date()}")
print(f"Latest last sale:    {latest_last_sale.date()}")

print("\nLast Sale Period:")
print(f"Within last 30 days:    {sold_last_30_days}")
print(f"31 - 90 days ago:       {sold_31_90_days}")
print(f"91 - 180 days ago:      {sold_91_180_days}")
print(f"181 - 365 days ago:     {sold_181_365_days}")
print(f"More than 365 days ago: {sold_over_365_days}")

# ---------------------------------------------------------
# 8. Optional detailed table
# ---------------------------------------------------------

missing_product_dates = missing_product_dates.sort_values(
    "Last_Sale_Date",
    ascending=False
)

print("\n========== PRODUCT DETAIL ==========")

print(
    missing_product_dates[
        [
            "Stock Code",
            "First_Sale_Date",
            "Last_Sale_Date",
            "Days_Since_Last_Sale"
        ]
    ].to_string(index=False)
)

========== 677 MISSING PRODUCT TIME SUMMARY ==========

Missing products: 677

Earliest first sale: 2025-02-09
Latest last sale:    2026-09-02

Last Sale Period:
Within last 30 days:    24
31 - 90 days ago:       48
91 - 180 days ago:      70
181 - 365 days ago:     203
More than 365 days ago: 332

========== PRODUCT DETAIL ==========
     Stock Code First_Sale_Date Last_Sale_Date  Days_Since_Last_Sale
        8029186      2026-08-04     2026-09-02                     2
           LOVE      2025-02-28     2026-09-02                     2
            066      2025-12-17     2026-08-31                     4
    FPU330154PS      2025-08-26     2026-08-31                     4
           PU52      2026-08-11     2026-08-29                     6
           5978      2025-11-13     2026-08-29                     6
       E6246E01      2026-01-14     2026-08-28                     7
         GCX057      2026-01-04     2026-08-27                     8
         LL5472      2026-02-03     2026-08-24                    11
          T3790      2026-03-07     2026-08-24                    11
         AB614L      2026-06-14     2026-08-20                    15
      MN8255-42      2026-08-17     2026-08-17                    18
         A26032      2025-05-21     2026-08-15                    20
        MC05-36      2026-08-13     2026-08-13                    22
   BB010(31-36)      2025-09-09     2026-08-12                    23
    FPU330155PS      2025-09-12     2026-08-12                    23
        MP5143W      2026-06-16     2026-08-10                    25
        MP5148W      2026-06-15     2026-08-10                    25
         AB578W      2025-08-08     2026-08-10                    25
         AB592W      2025-12-07     2026-08-10                    25
         AB531W      2025-12-08     2026-08-10                    25
          33122      2026-04-13     2026-08-10                    25
      MN8255-43      2026-08-09     2026-08-09                    26
         AB550W      2025-08-17     2026-08-06                    29
          WR945      2025-05-30     2026-08-04                    31
          T3704      2026-01-29     2026-07-31                    35
       E7140B87      2026-03-29     2026-07-31                    35
           8127      2026-05-22     2026-07-30                    36
         904C29      2025-11-01     2026-07-28                    38
         583296      2026-03-31     2026-07-27                    39
           2312      2025-09-03     2026-07-26                    40
        TK36001      2025-12-16     2026-07-25                    41
          KK432      2025-12-24     2026-07-25                    41
       E7227E01      2026-03-20     2026-07-24                    42
           SP18      2025-11-07     2026-07-22                    44
      MN8255-40      2026-07-19     2026-07-19                    47
           MC15      2025-08-29     2026-07-19                    47
        MI23313      2025-12-18     2026-07-16                    50
         HM8022      2026-03-06     2026-07-16                    50
           MC01      2025-08-14     2026-07-16                    50
         AB577M      2025-11-08     2026-07-12                    54
        K276500      2025-02-12     2026-07-12                    54
         A01101      2025-05-09     2026-07-08                    58
            G01      2025-12-04     2026-07-07                    59
         LL5399      2026-04-28     2026-07-06                    60
          E7158      2025-07-30     2026-07-05                    61
         AB549B      2025-07-13     2026-07-05                    61
       MIX29000      2026-04-01     2026-07-05                    61
         T37511      2025-12-06     2026-07-04                    62
         AD3583      2025-10-15     2026-07-04                    62
         AB590M      2025-08-16     2026-07-03                    63
         JASF01      2025-08-03     2026-07-02                    64
          21880      2025-03-25     2026-06-30                    66
     FPU33015PC      2025-03-23     2026-06-29                    67
         300090      2025-02-13     2026-06-29                    67
       E6256E01      2026-02-12     2026-06-24                    72
     LF7199235L      2025-05-09     2026-06-23                    73
          PA112      2025-10-20     2026-06-23                    73
           8661      2025-02-15     2026-06-23                    73
         NO6008      2026-04-28     2026-06-21                    75
       E6213E32      2025-11-17     2026-06-21                    75
         GC8003      2025-10-20     2026-06-21                    75
          51918      2025-03-22     2026-06-20                    76
         AB618M      2025-11-10     2026-06-19                    77
       PLB6H029      2026-04-13     2026-06-19                    77
        MIXSTAR      2025-09-28     2026-06-18                    78
        CHANNEL      2026-02-08     2026-06-16                    80
           GB21      2025-11-23     2026-06-16                    80
          F2326      2025-07-22     2026-06-15                    81
          MO165      2025-12-24     2026-06-09                    87
           MC05      2025-08-25     2026-06-07                    89
         AB552W      2025-08-17     2026-06-06                    90
    FPU330157PS      2025-12-06     2026-06-05                    91
         AB515M      2025-08-14     2026-06-04                    92
         F2322W      2026-03-17     2026-06-03                    93
          GC169      2026-01-22     2026-06-03                    93
          B2805      2025-02-17     2026-06-02                    94
       SNS77200      2025-11-01     2026-06-01                    95
           MC13      2025-08-22     2026-06-01                    95
         AB933M      2025-07-04     2026-05-31                    96
    FPU330159PS      2025-10-22     2026-05-31                    96
         GCT105      2025-10-05     2026-05-31                    96
         AB933W      2026-04-05     2026-05-29                    98
         MD9630      2026-03-03     2026-05-29                    98
         RABBIT      2025-11-24     2026-05-29                    98
          886A1      2026-03-26     2026-05-26                   101
         E6244M      2025-12-31     2026-05-25                   102
          T3713      2026-02-02     2026-05-25                   102
        2024032      2026-01-26     2026-05-20                   107
      E6213E321      2026-02-20     2026-05-18                   109
         A26019      2025-03-13     2026-05-12                   115
         A01542      2025-02-10     2026-05-12                   115
           5250      2025-10-13     2026-05-12                   115
         F2325W      2026-01-02     2026-05-10                   117
          Y9030      2025-11-23     2026-05-10                   117
   BB010(25-30)      2025-09-28     2026-05-09                   118
          71902      2025-11-29     2026-05-08                   119
           101H      2025-11-26     2026-05-08                   119
   ME012(25-30)      2025-08-31     2026-05-07                   120
          GCT99      2025-02-11     2026-05-07                   120
           PA70      2025-11-09     2026-05-04                   123
      LF231101M      2025-09-03     2026-05-03                   124
           V233      2025-11-26     2026-05-02                   125
       F2328E01      2026-03-19     2026-05-01                   126
        SNS5600      2025-12-22     2026-05-01                   126
        AB905B2      2025-09-21     2026-04-27                   130
        TK80001      2025-11-06     2026-04-27                   130
         AB599B      2025-07-17     2026-04-26                   131
         GC7Q37      2025-10-04     2026-04-25                   132
        SNS6700      2025-10-03     2026-04-25                   132
       SNS58001      2025-12-31     2026-04-22                   135
          GC167      2026-01-05     2026-04-19                   138
          72238      2025-11-23     2026-04-13                   144
          GC163      2025-12-13     2026-04-13                   144
          V8346      2025-11-22     2026-04-12                   145
          GC179      2025-10-03     2026-04-12                   145
          72248      2025-11-19     2026-04-12                   145
          A1001      2025-10-06     2026-04-10                   147
            A10      2025-12-18     2026-04-10                   147
            899      2025-12-07     2026-04-07                   150
   ME012(31-36)      2025-08-24     2026-04-06                   151
          JB008      2026-04-05     2026-04-05                   152
         TK5700      2025-12-24     2026-04-02                   155
           RS01      2026-02-27     2026-04-01                   156
        SNS3600      2025-05-23     2026-03-30                   158
           P847      2026-03-08     2026-03-29                   159
      E6213E299      2026-02-18     2026-03-29                   159
          T3779      2025-12-25     2026-03-27                   161
        AB906B2      2025-08-06     2026-03-26                   162
           ST85      2025-03-23     2026-03-25                   163
          GC180      2025-10-08     2026-03-24                   164
           NO08      2025-12-09     2026-03-23                   165
         179817      2025-10-17     2026-03-22                   166
        SNS7300      2026-01-04     2026-03-22                   166
          GC175      2026-01-10     2026-03-19                   169
       SNS75300      2025-11-03     2026-03-18                   170
       SNS75500      2025-11-28     2026-03-18                   170
        SNS5800      2025-06-13     2026-03-17                   171
          J7002      2025-07-20     2026-03-17                   171
          GD127      2025-12-20     2026-03-13                   175
         TK6500      2025-12-16     2026-03-09                   179
          E6201      2025-05-09     2026-03-09                   179
          00710      2025-09-13     2026-03-05                   183
        TK14000      2025-11-24     2026-03-05                   183
       SNS76200      2025-10-21     2026-03-02                   186
          E7190      2025-11-23     2026-03-01                   187
        AB596B2      2025-08-08     2026-02-28                   188
           5199      2025-09-10     2026-02-27                   189
          T3746      2025-11-20     2026-02-26                   190
          VENUS      2025-11-25     2026-02-26                   190
          PH013      2025-11-23     2026-02-24                   192
           5246      2025-09-13     2026-02-23                   193
    FPU330156PS      2025-10-25     2026-02-23                   193
          ML123      2025-11-19     2026-02-22                   194
          A0510      2025-02-26     2026-02-22                   194
      E6251E01M      2026-01-09     2026-02-22                   194
          16829      2025-09-15     2026-02-21                   195
         B04489      2025-02-09     2026-02-21                   195
          T3748      2025-08-27     2026-02-19                   197
         AB620W      2025-10-19     2026-02-16                   200
           P810      2025-05-10     2026-02-15                   201
          MC025      2025-11-09     2026-02-14                   202
        LBK2094      2025-05-10     2026-02-14                   202
          23081      2025-08-04     2026-02-12                   204
       E6217E08      2026-01-15     2026-02-10                   206
            LC1      2025-09-28     2026-02-09                   207
         AB978M      2025-08-15     2026-02-06                   210
        SNS6701      2025-10-07     2026-02-06                   210
         J18228      2026-02-06     2026-02-06                   210
          KK441      2025-12-20     2026-02-03                   213
         AB912W      2025-11-03     2026-02-03                   213
          B2802      2025-02-09     2026-02-02                   214
            101      2025-12-02     2026-02-01                   215
        AM19204      2025-12-15     2026-02-01                   215
          JAS16      2025-08-31     2026-02-01                   215
          NR053      2025-09-16     2026-02-01                   215
           X519      2025-05-10     2026-01-31                   216
          KW144      2025-09-14     2026-01-27                   220
         MP2175      2025-12-23     2026-01-26                   221
           8368      2025-10-25     2026-01-26                   221
     FPU33015PS      2025-05-10     2026-01-26                   221
        SNS8200      2025-07-06     2026-01-26                   221
           Y75L      2025-03-22     2026-01-26                   221
        ZH6666B      2025-05-09     2026-01-26                   221
         TK5400      2025-03-30     2026-01-22                   225
           D061      2026-01-22     2026-01-22                   225
         GP0012      2026-01-21     2026-01-21                   226
       E6213E44      2025-11-22     2026-01-20                   227
          A0290      2025-02-26     2026-01-19                   228
         6318A1      2025-05-31     2026-01-18                   229
       SNS49001      2025-12-20     2026-01-18                   229
          E6193      2025-05-29     2026-01-16                   231
        SNS4900      2025-08-31     2026-01-16                   231
   MD001(31-36)      2025-08-25     2026-01-15                   232
   ME010(31-36)      2025-08-24     2026-01-15                   232
          ML134      2025-09-18     2026-01-13                   234
           P801      2025-06-11     2026-01-12                   235
           5211      2025-09-09     2026-01-11                   236
          PH001      2025-09-04     2026-01-10                   237
         100588      2025-12-07     2026-01-05                   242
          72239      2025-11-08     2026-01-05                   242
         A01102      2025-02-11     2026-01-04                   243
         J18157      2025-05-09     2026-01-04                   243
          MC033      2025-11-11     2026-01-04                   243
         AB615W      2025-08-02     2026-01-04                   243
           3065      2025-10-03     2026-01-03                   244
         MM9233      2025-08-17     2026-01-03                   244
          T3717      2025-02-09     2026-01-02                   245
           G228      2026-01-02     2026-01-02                   245
         300136      2025-03-30     2026-01-01                   246
           P779      2025-05-20     2026-01-01                   246
          MF014      2025-09-22     2025-12-31                   247
         19861L      2025-03-27     2025-12-27                   251
         AB539W      2025-08-08     2025-12-25                   253
        5055912      2025-10-08     2025-12-25                   253
         PVC001      2025-10-25     2025-12-24                   254
           MC12      2025-07-23     2025-12-22                   256
           P788      2025-11-15     2025-12-21                   257
     MOOM SOCKS      2025-11-19     2025-12-19                   259
       1251861K      2025-05-09     2025-12-18                   260
         WR1102      2025-02-09     2025-12-17                   261
         TK3801      2025-02-21     2025-12-17                   261
         MD9623      2025-09-18     2025-12-17                   261
           2206      2025-03-21     2025-12-16                   262
           1127      2025-12-03     2025-12-13                   265
          ME014      2025-08-23     2025-12-13                   265
         200515      2025-05-26     2025-12-13                   265
           5436      2025-12-13     2025-12-13                   265
           Y75M      2025-03-24     2025-12-12                   266
         AB596B      2025-08-02     2025-12-12                   266
           2325      2025-11-02     2025-12-11                   267
          JAS01      2025-08-01     2025-12-11                   267
         GCX041      2025-12-11     2025-12-11                   267
         AB520B      2025-08-09     2025-12-11                   267
          ST331      2025-08-01     2025-12-10                   268
          EH213      2025-09-10     2025-12-09                   269
          AF401      2025-12-09     2025-12-09                   269
          24131      2025-12-08     2025-12-08                   270
         WR1104      2025-08-03     2025-12-08                   270
    FPU330159PC      2025-08-14     2025-12-08                   270
        TIANRUO      2025-11-27     2025-12-08                   270
         AB914W      2025-10-22     2025-12-07                   271
         MM9229      2025-05-10     2025-12-06                   272
         TK5600      2025-03-21     2025-12-06                   272
            PLM      2025-02-12     2025-12-06                   272
        SNS6400      2025-09-07     2025-12-05                   273
        SNS6301      2025-08-31     2025-12-05                   273
          T3744      2025-11-21     2025-12-05                   273
          T3776      2025-12-04     2025-12-05                   273
       K275800A      2025-02-09     2025-12-05                   273
       C582059C      2025-12-05     2025-12-05                   273
   ME010(25-30)      2025-10-04     2025-12-03                   275
         J18196      2025-10-07     2025-12-03                   275
          LV225      2025-10-28     2025-12-03                   275
       SNS74900      2025-11-16     2025-12-03                   275
            826      2025-11-10     2025-12-01                   277
       SNS76500      2025-10-28     2025-12-01                   277
          MF015      2025-08-25     2025-11-30                   278
         AB612M      2025-09-01     2025-11-30                   278
        SNS5000      2025-09-02     2025-11-29                   279
         FM1000      2025-08-19     2025-11-28                   280
         TK8000      2025-10-09     2025-11-27                   281
        SNS6800      2025-10-04     2025-11-26                   282
           SNS7      2025-02-12     2025-11-26                   282
        SNS6200      2025-09-18     2025-11-25                   283
          MML02      2025-05-10     2025-11-22                   286
          WS014      2025-08-01     2025-11-22                   286
         LXS925      2025-11-02     2025-11-21                   287
         J18187      2025-05-17     2025-11-20                   288
        SNS7500      2025-09-23     2025-11-20                   288
           7061      2025-08-01     2025-11-20                   288
        TK12002      2025-10-22     2025-11-19                   289
          MMS01      2025-08-23     2025-11-19                   289
         510872      2025-09-25     2025-11-18                   290
        SNS6300      2025-05-20     2025-11-17                   291
       SNS71601      2025-11-16     2025-11-16                   292
          FF007      2025-09-17     2025-11-15                   293
         LL5352      2025-02-16     2025-11-14                   294
         SHBSMP      2025-08-16     2025-11-14                   294
          63166      2025-09-14     2025-11-14                   294
       K273000A      2025-02-09     2025-11-13                   295
          Q9003      2025-10-01     2025-11-13                   295
         GD0113      2025-05-23     2025-11-12                   296

In [8]:
# =========================================================
# STEP 2.1 DIAGNOSTIC ONLY
# FIND WHICH DATA SOURCE THE 24 PRODUCTS ARE MISSING FROM
# DO NOT MODIFY PRODUCT MASTER
# =========================================================

import pandas as pd

# ---------------------------------------------------------
# 1. Get the 24 products sold within the last 30 days
# ---------------------------------------------------------

recent_24 = missing_product_dates[
    missing_product_dates["Days_Since_Last_Sale"] <= 30
].copy()

recent_24_codes = set(recent_24["Stock Code"])

print("Recent products to investigate:", len(recent_24_codes))


# ---------------------------------------------------------
# 2. Get Stock Codes from each source
# ---------------------------------------------------------

sale_codes = set(
    sale["Stock Code"].dropna().astype(str).str.strip()
)

purchase_codes = set(
    purchase["Stock Code"].dropna().astype(str).str.strip()
)

inventory_codes = set(
    inventory["Stock Code"].dropna().astype(str).str.strip()
)


# ---------------------------------------------------------
# 3. Check each of the 24 products
# ---------------------------------------------------------

check_24 = recent_24[
    ["Stock Code", "Last_Sale_Date", "Days_Since_Last_Sale"]
].copy()

check_24["Stock Code"] = (
    check_24["Stock Code"]
    .astype(str)
    .str.strip()
)

check_24["In Sales"] = check_24["Stock Code"].isin(sale_codes)

check_24["In Purchase"] = check_24["Stock Code"].isin(purchase_codes)

check_24["In Inventory"] = check_24["Stock Code"].isin(inventory_codes)


# ---------------------------------------------------------
# 4. Identify WHICH SOURCE is missing
# ---------------------------------------------------------

def identify_missing_source(row):

    missing = []

    if not row["In Purchase"]:
        missing.append("Purchase")

    if not row["In Inventory"]:
        missing.append("Inventory")

    if len(missing) == 0:
        return "None"

    return " + ".join(missing)


check_24["Missing From"] = check_24.apply(
    identify_missing_source,
    axis=1
)


# ---------------------------------------------------------
# 5. Show result for all 24 products
# ---------------------------------------------------------

print("\n========== 24 RECENT PRODUCTS ==========")

print(
    check_24[
        [
            "Stock Code",
            "Last_Sale_Date",
            "In Sales",
            "In Purchase",
            "In Inventory",
            "Missing From"
        ]
    ].to_string(index=False)
)


# ---------------------------------------------------------
# 6. Summary
# ---------------------------------------------------------

print("\n========== MISSING SOURCE SUMMARY ==========")

print(check_24["Missing From"].value_counts())


# ---------------------------------------------------------
# 7. Separate suspicious groups
# ---------------------------------------------------------

missing_purchase_only = check_24[
    (check_24["In Purchase"] == False) &
    (check_24["In Inventory"] == True)
]

missing_inventory_only = check_24[
    (check_24["In Purchase"] == True) &
    (check_24["In Inventory"] == False)
]

missing_both = check_24[
    (check_24["In Purchase"] == False) &
    (check_24["In Inventory"] == False)
]


print("\nMissing from PURCHASE only:")
print(len(missing_purchase_only))

print("\nMissing from INVENTORY only:")
print(len(missing_inventory_only))

print("\nMissing from BOTH Purchase + Inventory:")
print(len(missing_both))

Recent products to investigate: 24

========== 24 RECENT PRODUCTS ==========
  Stock Code Last_Sale_Date  In Sales  In Purchase  In Inventory         Missing From
     8029186     2026-09-02      True        False         False Purchase + Inventory
        LOVE     2026-09-02      True        False         False Purchase + Inventory
         066     2026-08-31      True        False         False Purchase + Inventory
 FPU330154PS     2026-08-31      True        False         False Purchase + Inventory
        PU52     2026-08-29      True        False         False Purchase + Inventory
        5978     2026-08-29      True        False         False Purchase + Inventory
    E6246E01     2026-08-28      True        False         False Purchase + Inventory
      GCX057     2026-08-27      True        False         False Purchase + Inventory
      LL5472     2026-08-24      True        False         False Purchase + Inventory
       T3790     2026-08-24      True        False         False Purchase + Inventory
      AB614L     2026-08-20      True        False         False Purchase + Inventory
   MN8255-42     2026-08-17      True        False         False Purchase + Inventory
      A26032     2026-08-15      True        False         False Purchase + Inventory
     MC05-36     2026-08-13      True        False         False Purchase + Inventory
BB010(31-36)     2026-08-12      True        False         False Purchase + Inventory
 FPU330155PS     2026-08-12      True        False         False Purchase + Inventory
     MP5143W     2026-08-10      True        False         False Purchase + Inventory
     MP5148W     2026-08-10      True        False         False Purchase + Inventory
      AB578W     2026-08-10      True        False         False Purchase + Inventory
      AB592W     2026-08-10      True        False         False Purchase + Inventory
      AB531W     2026-08-10      True        False         False Purchase + Inventory
       33122     2026-08-10      True        False         False Purchase + Inventory
   MN8255-43     2026-08-09      True        False         False Purchase + Inventory
      AB550W     2026-08-06      True        False         False Purchase + Inventory

========== MISSING SOURCE SUMMARY ==========
Missing From
Purchase + Inventory    24
Name: count, dtype: int64

Missing from PURCHASE only:
0

Missing from INVENTORY only:
0

Missing from BOTH Purchase + Inventory:
24

========== DATA QUALITY INSIGHT ==========

24 products were sold within the last 30 days.

Sales Data:      FOUND
Purchase Data:   NOT FOUND
Inventory Data:  NOT FOUND

Finding:
These 24 recently sold products cannot be matched with the currently
available Purchase data or the current Inventory snapshot.

Insight:
This is a cross-source data mismatch.

Possible Reason:
The Purchase history may be incomplete, and the Inventory data is only
a current snapshot.

Current Decision:
🟡 DATA CHECK REQUIRED

Do NOT treat these products as having zero Buying Price or zero Inventory.

Next Action:
Get more historical Purchase data and check these 24 products again.

If they are found:
→ Historical data coverage explains the missing values.

If they are still not found:
→ Further data-quality investigation is required.

==========================================

Step-2.1- | Step | Group | Selling Price | Buying Price | On Hand Qty | Can 677 continue? |
|---|---|---|---|---|---|
| 2. Group Products | Needed | Price Range needs price | — | — | ⚠️ Partially |
| 3. ABC Analysis | — | — | — | — | ✅ Yes |
| 4. Sales Velocity | — | — | — | — | ✅ Yes |
| 5. Inventory Position | — | — | — | **Needed** | ❌ Cannot calculate |
| 6. Sales Trend | — | — | — | — | ✅ Yes |
| 7. Profitability | — | Selling/value data needed | **Needed** | — | ❌ if price/cost unavailable |
| 8. Final Decision | Uses previous results | Uses previous results | Uses previous results | Uses previous results | ⚠️ Cannot give complete recommendation |

Step 2.2 PM valitaiton

We need to validate 5 things:
1. Total products
2. Duplicate Stock Codes
3. Missing Stock Codes / Descriptions
4. Source coverage
5. Current inventory fields

In [9]:
# =========================================================
# STEP 2 - PRODUCT MASTER VALIDATION
# Diagnostic only - does NOT modify data
# =========================================================


print("======================================")
print("STEP 2 - PRODUCT MASTER VALIDATION")
print("======================================")


# =========================================================
# 1. TOTAL PRODUCTS
# =========================================================

print("\n1. PRODUCT COUNT")

print("Product Master rows:", len(product_master))
print(
    "Unique Stock Codes:",
    product_master["Stock Code"].nunique()
)


# =========================================================
# 2. CHECK DUPLICATE STOCK CODES
# =========================================================

duplicate_codes = product_master[
    product_master["Stock Code"].duplicated(keep=False)
]

print("\n2. DUPLICATE CHECK")

print(
    "Duplicate Stock Code rows:",
    len(duplicate_codes)
)

if len(duplicate_codes) > 0:
    print("\nDuplicate products:")
    print(
        duplicate_codes[
            ["Stock Code", "Description"]
        ].to_string(index=False)
    )


# =========================================================
# 3. CHECK BASIC PRODUCT INFORMATION
# =========================================================

print("\n3. BASIC INFORMATION CHECK")

print(
    "Missing Stock Code:",
    product_master["Stock Code"].isna().sum()
)

print(
    "Missing Description:",
    product_master["Description"].isna().sum()
)

print(
    "Missing Group:",
    product_master["Group"].isna().sum()
)


# =========================================================
# 4. CHECK SOURCE COVERAGE
# =========================================================

print("\n4. SOURCE COVERAGE")

print(
    "Products appearing in Sale:",
    product_master["In Sale"].sum()
)

print(
    "Products appearing in Inventory:",
    product_master["In Inventory"].sum()
)

print(
    "Products appearing in Purchase:",
    product_master["In Purchase"].sum()
)


print("\nSource combinations:")

print(
    product_master[
        [
            "In Sale",
            "In Inventory",
            "In Purchase"
        ]
    ]
    .value_counts()
)


# =========================================================
# 5. CURRENT INVENTORY INFORMATION
# =========================================================

print("\n5. CURRENT INVENTORY FIELD CHECK")

print(
    "Missing Selling Price:",
    product_master["Selling Price"].isna().sum()
)

print(
    "Missing Buying Price:",
    product_master["Buying Price"].isna().sum()
)

print(
    "Missing On Hand Qty:",
    product_master["On Hand Qty"].isna().sum()
)


# =========================================================
# 6. CHECK INVENTORY PRODUCTS ONLY
# =========================================================

current_products = product_master[
    product_master["In Inventory"] == True
]

print("\n6. CURRENT INVENTORY PRODUCTS ONLY")

print(
    "Current inventory products:",
    len(current_products)
)

print(
    "Missing Group:",
    current_products["Group"].isna().sum()
)

print(
    "Missing Selling Price:",
    current_products["Selling Price"].isna().sum()
)

print(
    "Missing Buying Price:",
    current_products["Buying Price"].isna().sum()
)

print(
    "Missing On Hand Qty:",
    current_products["On Hand Qty"].isna().sum()
)


# =========================================================
# 7. FINAL STRUCTURE
# =========================================================

print("\n7. PRODUCT MASTER COLUMNS")

print(product_master.columns.tolist())


print("\n======================================")
print("VALIDATION COMPLETE")
print("======================================")

======================================
STEP 2 - PRODUCT MASTER VALIDATION
======================================

1. PRODUCT COUNT
Product Master rows: 1320
Unique Stock Codes: 1320

2. DUPLICATE CHECK
Duplicate Stock Code rows: 0

3. BASIC INFORMATION CHECK
Missing Stock Code: 0
Missing Description: 1
Missing Group: 678

4. SOURCE COVERAGE
Products appearing in Sale: 1196
Products appearing in Inventory: 643
Products appearing in Purchase: 15

Source combinations:
In Sale  In Inventory  In Purchase
True     False         False          677
         True          False          513
False    True          False          115
                       True             9
True     True          True             6
Name: count, dtype: int64

5. CURRENT INVENTORY FIELD CHECK
Missing Selling Price: 677
Missing Buying Price: 677
Missing On Hand Qty: 677

6. CURRENT INVENTORY PRODUCTS ONLY
Current inventory products: 643
Missing Group: 1
Missing Selling Price: 0
Missing Buying Price: 0
Missing On Hand Qty: 0

7. PRODUCT MASTER COLUMNS
['Branch', 'Stock Code', 'Description', 'Group', 'Selling Price', 'Buying Price', 'On Hand Qty', 'In Sale', 'In Inventory', 'In Purchase']

======================================
VALIDATION COMPLETE
======================================

in this the missing descriptiton is the red alarm system that the user-side needed to make to get the better useful insightable results .... this is the main thing we does not allow and we can make rules based on this ...- 🔴 user red sign -1

File1- Missing data question2 - 
Alarm System 
in this the missing descriptiton is the red alarm system that the user-side needed to make to get the better useful insightable results .... this is the main thing we does not allow and we can make rules based on this ...- 🔴 user red sign -1 - action to solve this - 
For every Product Master product with a missing Description:
solution 1-
What is the Stock Code?
Does it exist in Sale / Inventory / Purchase?
In which source is the description missing?
What is the first and last date that stock code appears in each source?
What is the latest record date? we can find the data 
Chatbot answer- 
	Data Source	Branch	Date	Missing Description Count
0	Sale	Ashley	2026-03-12	1
1	Sale	Ashley	2026-03-27	1
2	Sale	Ashley	2026-04-12	1
3	Inventory	Ashley	2026-09-04	1
based on this if there is the missing data at  description coumn only  ....it means when the purchase data is comming , the data entery is missing at the desctiption part and  so these continue sale data and inventory has misisng data continue . action needed - remind the staff to add the description inside this. task alarm.

File2 - 
Yes. What you found is useful, and I would formalize it as a **data-quality alarm rule**.

### Missing Data Question 2 — Description Alarm

Your reasoning is:

> If a product has a missing `Description`, and that same Stock Code continues appearing later in Sale and Inventory, the problem likely started earlier during data entry and then propagated through later records.

Your example supports that pattern:

```text
Sale       Ashley   2026-03-12   missing Description
Sale       Ashley   2026-03-27   missing Description
Sale       Ashley   2026-04-12   missing Description
Inventory  Ashley   2026-09-04   missing Description
```

So this should become:

```text
🔴 USER-SIDE RED ALARM
Missing Product Description
```

### Rule

For every Product Master product with missing `Description`, check:

```text
Stock Code
↓
Which source contains it?
Sale / Purchase / Inventory
↓
First appearance date
↓
Last appearance date
↓
Latest record date
↓
Is Description still missing?
```

### Business meaning

If the Description remains missing across later records:

> This is not only an analysis problem. It is a **master-data maintenance problem**.

Because Description is needed later for:

```text
Category
Product grouping
Product comparison
Business insight
Purchasing decision
```

### User-side action

Your action rule can be:

> 🔴 **Action Required — Add Product Description**

The system should tell staff:

```text
Stock Code: XXXXX
Description is missing.

This product appears in:
Sale → Yes
Inventory → Yes
Purchase → No/Yes

Please add or correct the product Description.
```

### Important improvement

I would avoid saying with 100% certainty:

> “The Purchase data entry caused the missing description”

unless you actually have the earlier purchase record showing that it was first missing there.

Safer system logic is:

> **The Description is missing and continues across later datasets. The earliest available source should be investigated to identify where the missing master data began.**

That makes your alarm system more reliable.

So this becomes your first important **user-facing data quality rule**:

**🔴 Red Alarm #1 — Missing Description → staff must correct master data before Category analysis can be trusted.**

This is a strong addition to your system because now you are not only doing analysis; you are also detecting **data-entry problems that reduce decision quality**.

Continue with the description alarm

- :chatgpt-content-reference{index="0"}

In [10]:
# =========================================================
# SIMPLE MISSING DESCRIPTION REPORT
# Source + Branch + Date + Missing Count
# =========================================================

import pandas as pd


def missing_description_report(data, source_name, date_column):

    df = data.copy()

    # Convert date
    df[date_column] = pd.to_datetime(
        df[date_column],
        errors="coerce"
    )

    # Find missing Description
    missing = df[
        df["Description"].isna()
        | df["Description"].astype("string").str.strip().isin(["", "nan", "None", "null"])
    ].copy()

    # Keep only date
    missing["Date"] = missing[date_column].dt.date

    # Count missing rows by branch and date
    result = (
        missing
        .groupby(["Branch", "Date"], dropna=False)
        .size()
        .reset_index(name="Missing Description Count")
    )

    # Add source
    result.insert(0, "Data Source", source_name)

    return result

In [11]:
sale_missing = missing_description_report(
    sale,
    "Sale",
    "Date"
)

inventory_missing = missing_description_report(
    inventory,
    "Inventory",
    "Last Updated"
)

purchase_missing = missing_description_report(
    purchase,
    "Purchase",
    "Date"
)

In [12]:
missing_description = pd.concat(
    [
        sale_missing,
        inventory_missing,
        purchase_missing
    ],
    ignore_index=True
)

missing_description

  Data Source  Branch        Date  Missing Description Count
0        Sale  Ashley  2026-03-12                          1
1        Sale  Ashley  2026-03-27                          1
2        Sale  Ashley  2026-04-12                          1
3   Inventory  Ashley  2026-09-04                          1

based on this missing data at  description coumn only  ....it means when the purchase data is comming , the data entery is missing at the desctiption part and  so these continue sale data and inventory has misisng data continue . action needed - remind the staff to add the description inside this. task alarm. this is for the missing data handelling rule .. lets go to the continue tothe part of Create Step 3 — Product Grouping,,,

Step 3 - Group The Products

STEP 3 — GROUP PRODUCTS

3A. Category
    ✅ 3.1 Collect all-branch descriptions
    ✅ 3.2 Discover description names
    ✅ 3.3 Check description consistency
    ⏭ 3.4 Define Category rules
    ⬜ 3.5 Assign Category to Stock Code
    ⬜ 3.6 Add Category to Ashley Product Master

3B. Price Range
    ⬜ Low / Mid / High

In [13]:
# preparation for the stpe 3 
# ========================================================
# =========================================================
# PREPARATION FOR STEP 3
# CREATE ALL_SALES + ADD GROUP FROM INVENTORY
# =========================================================

all_sales = sale.copy()

# Clean Stock Code
all_sales["Stock Code"] = (
    all_sales["Stock Code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Clean Description
all_sales["Description"] = (
    all_sales["Description"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# ---------------------------------------------------------
# CREATE STOCK CODE -> GROUP MAPPING FROM INVENTORY
# ---------------------------------------------------------

inventory_group = inventory[
    ["Stock Code", "Group"]
].copy()

inventory_group["Stock Code"] = (
    inventory_group["Stock Code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

inventory_group["Group"] = (
    inventory_group["Group"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# One Stock Code = One Group
inventory_group = (
    inventory_group
    .dropna(subset=["Stock Code", "Group"])
    .drop_duplicates(subset=["Stock Code"])
)

# ---------------------------------------------------------
# ADD GROUP TO SALES
# ---------------------------------------------------------

all_sales = all_sales.merge(
    inventory_group,
    on="Stock Code",
    how="left"
)

print("========== ALL SALES CREATED ==========")
print("Total Sales Rows:", len(all_sales))
print("Unique Stock Codes:", all_sales["Stock Code"].nunique())
print("Branches:", all_sales["Branch"].nunique())

print("\nGroup Found:")
print(all_sales["Group"].notna().sum())

print("\nGroup Missing:")
print(all_sales["Group"].isna().sum())

========== ALL SALES CREATED ==========
Total Sales Rows: 9459
Unique Stock Codes: 1196
Branches: 1

Group Found:
5240

Group Missing:
4219

In [14]:
# =========================================================
# STEP 3 - GROUP THE PRODUCTS
# 3A. CATEGORY FROM DESCRIPTION
# =========================================================


# ---------------------------------------------------------
# 3.1 COLLECT DESCRIPTIONS FROM ALL BRANCHES
# ---------------------------------------------------------

description_data = all_sales[
    [
        "Stock Code",
        "Description"
    ]
].copy()


# Clean Description
description_data["Description"] = (
    description_data["Description"]
    .astype("string")
    .str.strip()
    .str.upper()
)


# Remove missing and empty descriptions
description_data = description_data[
    description_data["Description"].notna()
    & (description_data["Description"] != "")
]


# Remove duplicate Stock Code + Description combinations
description_data = (
    description_data
    .drop_duplicates(
        subset=["Stock Code", "Description"]
    )
)


# ---------------------------------------------------------
# CHECK RESULT
# ---------------------------------------------------------

print("========== DESCRIPTION DATA ==========")

print("\nUnique Stock Codes:")
print(description_data["Stock Code"].nunique())

print("\nUnique Descriptions:")
print(description_data["Description"].nunique())

print("\nSample:")
print(
    description_data
    .head(20)
    .to_string(index=False)
)

========== DESCRIPTION DATA ==========

Unique Stock Codes:
1195

Unique Descriptions:
311

Sample:
Stock Code        Description
     71641               SMIL
SNS788001A        SHWENANNSAN
  E7164B71              LUOFU
  E6217E38              LUOFU
     E6217              LUOFU
 SNS75900A       SHWE NAN SAN
      A067                MIU
    SLA008             PINNIP
        M6         WILD HORSE
     F2320              LOUFU
 SNS79000A        SHWENANNSAN
 SNS762001         ကလေးကျောက်
     E7885          MALE SHOE
  SNS77500       SHWE NAN SAN
      KKNW ကြိူးကြာနီ မ သားရေ
    MK7124            MALDINI
    A01617        ယုန်ဖြူကျား
BLUE CAMEL         BLUE CAMEL
     3116S             LABUBU
    2611B4          JYLANDJYL

In [15]:
print (all_sales.head(20).to_string(index=False))

Branch       Date     Time      Slip ID  Slip Number  Line No         Line ID Stock Code        Description  Selling Price  Qty  UOM  Discount Amount  Amount  Net Amount Location  Buying Price   Profit  Profit Margin % Group
Ashley 2026-09-04 17:24:11 20260904-001            1        1 20260904-001-01      71641               SMIL        15500.0  1.0 Each              0.0 15500.0     15500.0   Ashley      11500.00  4000.00            25.81  LADY
Ashley 2026-09-04 17:24:11 20260904-001            1        2 20260904-001-02 SNS788001A        SHWENANNSAN        12500.0  1.0 Each              0.0 12500.0     12500.0   Ashley       8800.00  3700.00            29.60  LADY
Ashley 2026-09-04 17:24:11 20260904-001            1        3 20260904-001-03   E7164B71              LUOFU        32000.0  1.0 Each              0.0 32000.0     32000.0   Ashley      22700.00  9300.00            29.06  LADY
Ashley 2026-09-04 17:24:11 20260904-001            1        4 20260904-001-04   E6217E38              LUOFU        42500.0  1.0 Each              0.0 42500.0     42500.0   Ashley      31000.00 11500.00            27.06   MEN
Ashley 2026-09-04 17:24:11 20260904-001            1        5 20260904-001-05      E6217              LUOFU        41500.0  1.0 Each              0.0 41500.0     41500.0   Ashley      31000.00 10500.00            25.30   MEN
Ashley 2026-09-04 17:24:45 20260904-002            2        1 20260904-002-01  SNS75900A       SHWE NAN SAN         9500.0  1.0 Each              0.0  9500.0      9500.0   Ashley       6600.00  2900.00            30.53  LADY
Ashley 2026-09-04 17:24:45 20260904-002            2        2 20260904-002-02       A067                MIU        21500.0  1.0 Each              0.0 21500.0     21500.0   Ashley      16200.00  5300.00            24.65  LADY
Ashley 2026-09-04 17:25:20 20260904-003            3        1 20260904-003-01      E6217              LUOFU        41500.0  1.0 Each              0.0 41500.0     41500.0   Ashley      31000.00 10500.00            25.30   MEN
Ashley 2026-09-04 17:25:20 20260904-003            3        2 20260904-003-02     SLA008             PINNIP        29000.0  1.0 Each              0.0 29000.0     29000.0   Ashley      22200.00  6800.00            23.45  LADY
Ashley 2026-09-04 17:25:20 20260904-003            3        3 20260904-003-03         M6         WILD HORSE         9500.0  1.0 Each              0.0  9500.0      9500.0   Ashley       3995.80  5504.20            57.94   MEN
Ashley 2026-09-04 18:31:06 20260904-004            4        1 20260904-004-01      F2320              LOUFU        34500.0  1.0 Each              0.0 34500.0     34500.0   Ashley      26698.37  7801.63            22.61  LADY
Ashley 2026-09-04 18:31:06 20260904-004            4        2 20260904-004-02  SNS79000A        SHWENANNSAN        12500.0  1.0 Each              0.0 12500.0     12500.0   Ashley       9000.00  3500.00            28.00  LADY
Ashley 2026-09-03 18:40:31 20260903-001            1        1 20260903-001-01  SNS762001         ကလေးကျောက်         8500.0  1.0 Each              0.0  8500.0      8500.0   Ashley       6500.00  2000.00            23.53 CHILD
Ashley 2026-09-03 18:40:31 20260903-001            1        2 20260903-001-02      E7885          MALE SHOE        23500.0  1.0 Each              0.0 23500.0     23500.0   Ashley      14800.00  8700.00            37.02 CHILD
Ashley 2026-09-03 18:40:31 20260903-001            1        3 20260903-001-03   SNS77500       SHWE NAN SAN        10500.0  1.0 Each              0.0 10500.0     10500.0   Ashley       7500.00  3000.00            28.57  LADY
Ashley 2026-09-03 18:40:31 20260903-001            1        4 20260903-001-04       KKNW ကြိူးကြာနီ မ သားရေ        19000.0  1.0 Each              0.0 19000.0     19000.0   Ashley      12804.69  6195.31            32.61  LADY
Ashley 2026-09-03 18:40:31 20260903-001            1        5 20260903-001-05     MK7124            MALDINI        56000.0  1.0 Each              0.0 56000.0     56000.0   Ashley      28000.00 28000.00            50.00   MEN
Ashley 2026-09-03 18:44:45 20260903-002            2        1 20260903-002-01     A01617        ယုန်ဖြူကျား        19000.0  1.0 Each              0.0 19000.0     19000.0   Ashley      12510.23  6489.77            34.16   MEN
Ashley 2026-09-03 18:44:45 20260903-002            2        2 20260903-002-02 BLUE CAMEL         BLUE CAMEL        14500.0  1.0 Each              0.0 14500.0     14500.0   Ashley      12780.22  1719.78            11.86   MEN
Ashley 2026-09-03 18:44:45 20260903-002            2        3 20260903-002-03      3116S             LABUBU        22000.0  1.0 Each              0.0 22000.0     22000.0   Ashley      14133.33  7866.67            35.76 CHILD

In [16]:
# ---------------------------------------------------------
# 3.2 DESCRIPTION + GROUP RELATIONSHIPS
# ARRANGE SAME DESCRIPTION TOGETHER
# ---------------------------------------------------------

description_summary = (
    all_sales[
        ["Stock Code", "Description", "Group"]
    ]
    .drop_duplicates()
    .groupby(
        ["Description", "Group"],
        dropna=False
    )
    .agg(
        Product_Count=("Stock Code", "nunique")
    )
    .reset_index()
)

# Sort:
# 1. Description A -> Z
# 2. Product Count smallest -> largest
description_summary = description_summary.sort_values(
    by=["Description", "Product_Count"],
    ascending=[True, True]
)

print("========== DESCRIPTION + GROUP SUMMARY ==========")

print(
    description_summary
    .to_string(index=False)
)
total_descriptions = all_sales["Description"].nunique(dropna=False)

print("Total descriptions:", total_descriptions)
na_description_count = all_sales.loc[
    all_sales["Group"].isna(),
    "Description"
].nunique()

print("Descriptions with N/A Group:", na_description_count)

========== DESCRIPTION + GROUP SUMMARY ==========
                  Description     Group  Product_Count
                        9 TO5      LADY              1
                          999      <NA>              1
                         9TO5      LADY              2
                      A FITCH       MEN              1
                    AANDFICTH       MEN              1
                      AB WALK     CHILD              6
                      AB WALK      LADY              8
                      AB WALK       MEN              8
                      AB WALK      <NA>             24
                    AB WALK23     CHILD              1
                    AB WALKER     CHILD              1
                      AB WALL       MEN              1
                       ABWALK     CHILD              1
                       ABWALK      LADY              1
                       ABWALK       MEN              1
                       ABWALK      <NA>              4
                    ACE SHOES      <NA>              1
                         ADDA       MEN              1
                         ADDA      <NA>              1
                        ADIDA      <NA>              1
                       ADIDAS      SOCK              1
                       ADIDAS      LADY              2
                       ADIDAS      <NA>              2
                     AEROSOFT      <NA>             14
                        BAOJI      <NA>              1
                  BAOJI SHOES      <NA>              1
                      BEE BEE      LADY              2
                      BEE BEE      <NA>              5
                        BELLA      <NA>              1
                        BELLA      LADY              3
                     BELONGSE      <NA>              1
                   BLUE CAMEL       MEN              1
                   BRAZILANKT      <NA>              1
                    BRAZILANT      <NA>              1
                     BRAZILON      <NA>              1
                       BRAZIN      <NA>              1
                     BRAZLIAN      LADY              1
                     BRAZLLAN      <NA>              2
                      CARTAGO      <NA>              3
                       CHANEL      LADY              2
                       CHANEL      <NA>              2
                      CHANNEL      <NA>              1
                      CHANNEL      LADY              2
                       CHARMI      <NA>              1
          CHINA BOOT(မိုးစီး)       MEN              1
                      CLASSIC      LADY              1
                      CONFORM      LADY              1
                        CROCS     CHILD              5
                        CROSS      <NA>              1
                      CRYSTAL      BABY              1
                      CRYSTAL      LADY              2
                        CUFFY      <NA>              1
                         DIOR      <NA>              1
                      DOUBLED     CHILD              9
                   DR MARTINE      <NA>              2
                   DR.MARTINE      <NA>              1
                         EDDY       MEN              1
                         EDDY      LADY              2
                         EDDY     CHILD              3
                         EDDY      <NA>              6
                        EIISA      <NA>              1
                        ELISA      LADY              9
                        ELISA      <NA>             18
                        ELISE      <NA>              1
                         ELSA      <NA>              1
                          EVA      BABY              1
                          EVA     CHILD              1
                      FARTAIN      <NA>              1
                 FARTIN STYLE      <NA>              1
                      FASHION       MEN              1
                      FASHION     CHILD              5
                      FASHION      LADY             10
                      FASHION      <NA>             23
                FASHION MJ608      <NA>              1
                FASHION SHOES      <NA>              1
          FASHION SPORT TG300      <NA>              1
          FASHION(CHILD SHOE)     CHILD              2
                         FEAD      LADY              1
                      FITTLOP      LADY              1
                  FJ FOOTWEAR       MEN              1
                     FJ SPORT      <NA>              1
                      FLOWERS      LADY              1
                    FOOT NIKS      <NA>              6
                      FOOTNIK      <NA>              1
                     FOOTNIKE       MEN              1
                     FOOTNIKS       MEN              2
                     FOOTNIKS      <NA>              3
                     FOOTNIKS     CHILD              7
                     FOOTNILK      <NA>              6
                      FORTUNE      <NA>              1
                     FRESHYON      LADY              2
                     FRESHYON      <NA>              3
                         FROG      LADY              1
                        FSRAW      <NA>              1
                      FTTIIOD      <NA>              1
                       GAMBOL       MEN              1
                       GAMBOL      <NA>              2
                     GD SHOES      <NA>              1
                        GIFTS     CHILD              1
                        GIFTS      <NA>              1
                     GOLDCITY      <NA>              1
                  GOLDEN DUCK      LADY              5
                  GOLDEN DUCK      <NA>             15
                   GOLDENDUCK      <NA>              7
                       GOODDY      <NA>              7
                       GOODDY      LADY              9
                        GOODY      <NA>              1
                    GOVY SOFT      <NA>              4
                    GOVY SOFT     CHILD              5
                    GOVY SOFT       MEN              7
                     GOVYSOFT      <NA>              1
                     GRANDEUR      <NA>              1
                     GRANDEUR       MEN              2
                        GUCCI       MEN              1
                        GUCCI      LADY              4
                        GUCCI      <NA>              8
                         GUCI     CHILD              1
                         GUCI      LADY              2
                         GUCI       MEN              7
                         GUCI      <NA>             21
                   HAPPY BABY     CHILD              2
                    HAVALANAS      <NA>              1
                        HORSE       MEN              1
                     HOTMARZZ      <NA>              1
                       HUMMER       MEN              1
                       HUMMER     CHILD              6
                       HUMMER      <NA>             17
                      I SHOES      <NA>              1
                          IMM      <NA>              1
                         IMMI      LADY              1
                         IMMI      <NA>              1
                      IQ SOFT      <NA>              2
                      IQ SOFT       MEN              5
                       IQSOFT      <NA>              1
                       JABBIT      <NA>              1
                       JABBIT      SOCK              4
                      JANAGON      <NA>              1
                     JANAKORN      LADY              2
                        JASSH       MEN              1
                        JASSY       MEN              1
                        JASSY      <NA>              2
                       JIBBIT ASSEORIES              6
                      JINZUDA      <NA>              1
                        JJ168      <NA>              1
                  JOHN MARTAN      <NA>              1
                  JOHN MARTAN       MEN              2
                   JOHNMARTAN      <NA>              1
                        JUMBO      <NA>              1
                    JYLANDJYL      LADY              1
                           K2     CHILD              2
                           K2      <NA>              2
                KHAING MARLAR      <NA>              1
                         KING      SOCK              1
                         KITO       MEN              1
                         KITO      LADY              3
                         KITO      <NA>              8
                    KM CRUSHY       MEN              3
                     KM CUSHY      <NA>              7
                       KONIKA      LADY              2
                     KULLANIT      BABY              1
                     KULLANIT      <NA>              4
                       KUROMI      <NA>              2
                       LABUBU     CHILD              2
                       LABUBU      <NA>              7
                      LACOSTE      <NA>              2
                         LAVA      LADY              2
                     LAVANDAR      <NA>              1
                     LAVENDAR      <NA>              1
                         LILY     CHILD              1
                         LILY      <NA>             14
                         LILY      LADY             19
                      LIMITED      <NA>              1
                        LOLLA      LADY             13
                        LOLLA      <NA>             22
                        LOUFO      <NA>              1
                        LOUFU     CHILD              1
                        LOUFU      LADY              2
                        LOUFU      <NA>              4
                         LOVE     CHILD              1
                        LUOFU      BABY              1
                        LUOFU     CHILD             11
                        LUOFU      LADY             21
                        LUOFU       MEN             24
                        LUOFU      <NA>             30
                           LV      <NA>              1
                      M QUEEN      LADY              1
                        MAGIE     CHILD              1
                        MALDI       MEN              3
                      MALDINI     CHILD              4
                      MALDINI       MEN             15
                      MALDINI      <NA>             41
                       MALDNI       MEN              1
                    MALE SHOE     CHILD              1
                   MALE SHOES     CHILD              1
                        MALEE      <NA>              1
                        MALEE      LADY              2
                   MARCO PONY      <NA>              1
                    MARCOPONY      LADY              2
                    MARCOPONY     CHILD              4
                    MARCOPONY      <NA>              6
                       MARINA     CHILD              1
                       MARINA      LADY              2
                       MARINA      <NA>              8
                       MARTEN       MEN              1
                       MARTEN      <NA>              1
                      MARTINE      <NA>              3
                       MASCOT      LADY              1
                       MASCOT      <NA>             13
                     MC QUEEN      <NA>              1
                       ME TOO      <NA>              1
                       MEIQIN      <NA>              1
                MEMBER'S MENU      <NA>              1
                      MI STAR       MEN              1
                     MINI CAT      <NA>              1
                       MISTAR       MEN              1
                          MIU      LADY              1
                          MIU      <NA>              1
                      MIU MIU      LADY              1
                      MIXSTAR     CHILD              1
                     MOO CHUU      <NA>              5
                       MOOCHU      LADY              1
                       MOOCHU      <NA>              1
                       MSMILE      <NA>              1
                        MUZZE      LADY              1
                        MUZZE      <NA>             13
                     NES STAR     CHILD              1
                     NEW STAR      LADY              2
                         NICE      <NA>              1
                         NIKE      LADY              1
                         NIKE      SOCK              1
                         NIKE      <NA>              4
                        NILIN      LADY              2
                        NILIN      <NA>              9
              NISA SHOES F-84      <NA>              1
                     NSA SHOE      <NA>              1
                    NSA SHOES      <NA>              1
                        OMEGA      <NA>              1
                       ORCHID      LADY              1
                       ORCHID      <NA>              2
                       ORIPES      <NA>              1
                  PADANA BLUE      LADY              1
                   PANDA BLUE       MEN              2
                    PANDABLUE     CHILD              1
                    PANDABLUE      <NA>              4
                         PEME      <NA>              1
                        PENNE      LADY              1
                        PENNE      <NA>              2
                       PINNIP      LADY              1
                       PINNIP      <NA>              1
                       PINNIP       MEN              6
                     PLAY BOY       MEN              1
                          PMP      <NA>              1
                         POLA     CHILD              1
                         PUMA      SOCK              1
                         PUMA      <NA>              1
                      Q SWEET      <NA>              3
                      Q SWEET      LADY              4
                       QSWEET      <NA>              2
                       QSWEET      LADY              3
                        QTRAL      <NA>              1
                          R/D      <NA>              1
                       RABBIT      <NA>              1
                      RAGAZZO      <NA>              1
                      RAINBOW      <NA>              2
                        RIDER      <NA>              8
                        RIOME      <NA>              1
                  RISING STAR      <NA>              1
                       ROSITA      <NA>              1
                  RUBBER STAR       MEN              1
                          RUN      <NA>              1
                     RUN FAST      <NA>              1
                          RVW      LADY              1
                         SALE       MEN              1
                      SENSINI      <NA>              1
                        SHDTR      <NA>              1
                       SHELAY      <NA>              1
                         SHOE     CHILD              1
                         SHOE       MEN              1
                         SHOE      <NA>              1
             SHOE SHINE WIPES      SOCK              1
                        SHOES      <NA>              1
                       SHOWER       MEN              4
                   SHOWER CHJ       MEN              1
                 SHWE NAN SAN       MEN              1
                 SHWE NAN SAN      <NA>             10
                 SHWE NAN SAN      LADY             17
      SHWE NAN SAN (ကလေးအဖြူ)     CHILD              1
          SHWE NAN SAN (မဖြူ)      LADY              1
      SHWE NAN SAN(ခွာငုံဖြူ)      LADY              1
SHWE NAN SAN(လယ်သာဖြူပုံမှန်)      LADY              1
   SHWE NAN SAN(လယ်သာြဖူOVER)      LADY              1
                SHWE NANN SAN      <NA>             14
                 SHWE.NANNSAN      <NA>              2
                  SHWENAN SAN      LADY              1
                  SHWENANNSAN      LADY              7
                  SHWENANNSAN      <NA>             11
                       SIAEKR       MEN              1
                        SISCO      LADY              3
                        SISCO      <NA>              3
                           SM       MEN              1
                   SMFOOTWARE      <NA>              1
                         SMIL      LADY              2
                        SMILE      LADY              1
                        SMILE      <NA>              1
                 SMILE KUROMI      <NA>              1
          SNEAKER SHINE WIPES      SOCK              1
                         SNOW      <NA>              1
                         SOCK      SOCK              2
                         SOCK      <NA>              5
                        SOCKS      SOCK              1
                     SOGOLITE      <NA>              4
                       SPARTS      <NA>              1
                       SPIDER     CHILD              1
                       SPIDER      <NA>              2
                        SPORT       MEN              2
                        SPORT      <NA>              4
                        SPORT     CHILD              5
                       SPRING      LADY              1
                       SPRING      <NA>              5
                      STALKER       MEN              2
                      STALKER      <NA>              2
                    STEVENSAM      LADY              1
                      STICKER      LADY              1
                     STOR WOR      LADY              1
                        STRDJ      <NA>              1
                          SUP      <NA>              2
                       SUZUKI      LADY              3
                        SWEET      <NA>              1
                  SWEET HAPPY      <NA>              1
                   THAI STYLE       MEN              2
                    THIT KHAW      <NA>              1
                       TOMATO      <NA>              4
                      TOP ONE      LADY              1
                    TOTA LAND      <NA>              1
                           U2     SHOES              1
                     V.R.KIDS     CHILD              2
                        VENUS      <NA>              2
                      VERSACE      <NA>              2
                     VICTORIA      <NA>              1
                       WALKER      <NA>              1
                         WALL      <NA>              1
                       WARING      <NA>              1
                   WATER FISH      <NA>              3
                    WELL NINE      <NA>              1
                   WILD HORSE       MEN              1
                       WINKKI      <NA>              1
                WINKKI KT8439      <NA>              1
                  WORLD SWEET      <NA>              2
                           X3      SOCK              1
                     XLNYLMEL      LADY              1
                        YEEZI      <NA>              3
                        YEEZI       MEN              6
                  YEEZY SLIDE      <NA>              1
                          YES     CHILD              1
                  ZENITH CLUB       MEN              1
                  ZENITH CLUB      <NA>              1
                      ကင်းဖြူ       MEN              1
                      ကင်းဘတ်       MEN              1
                   ကလေးကျောက်     CHILD              1
              ကလေးကြိုးသိုင်း     CHILD              2
               ကလေးမိုးစိုစီး      <NA>              1

# ==========================================================
# STEP 4.6 — ABC CLASS + PRICE RANGE ANALYSIS
# ==========================================================

abc_price = pd.crosstab(
    product_master["ABC_Class"],
    product_master["Price Range"]
)

# Put columns in clear order
abc_price = abc_price.reindex(
    columns=["Low", "Mid", "High"],
    fill_value=0
)

# Add total
abc_price["Total"] = abc_price.sum(axis=1)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== ABC + PRICE RANGE ==========")

print(abc_price)

print("\n========== PERCENTAGE WITHIN EACH ABC CLASS ==========")

abc_price_percent = pd.crosstab(
    product_master["ABC_Class"],
    product_master["Price Range"],
    normalize="index"
) * 100

abc_price_percent = abc_price_percent.reindex(
    columns=["Low", "Mid", "High"],
    fill_value=0
)

print(
    abc_price_percent
    .round(2)
)

# ---------------------------------------------------------
# 3.2 DESCRIPTION + GROUP RELATIONSHIPS
# FIND SAFE DESCRIPTION -> GROUP PATTERNS
# FILL MISSING GROUPS
# ---------------------------------------------------------

In [17]:
# ---------------------------------------------------------
# 3.2 DESCRIPTION + GROUP RELATIONSHIPS
# FIND SAFE DESCRIPTION -> GROUP PATTERNS
# FILL MISSING GROUPS
# --------------------------------------------------------
# -FILL MISSING GROUP DATA
#
# SITUATION 1:
# Description has only ONE known Group
# -> SAFE -> Fill missing Group
#
# SITUATION 2:
# Description has MULTIPLE known Groups
# -> UNSAFE -> Keep <NA>
# ---------------------------------------------------------

import pandas as pd


# =========================================================
# STEP 1: COUNT BEFORE FILLING
# =========================================================

total_products = all_sales["Stock Code"].nunique()

missing_before = (
    all_sales.loc[
        all_sales["Group"].isna(),
        "Stock Code"
    ]
    .nunique()
)


# =========================================================
# STEP 2: CLEAN / REDUCE DESCRIPTION
#
# Purpose:
# Reduce formatting differences into ONE description pattern.
#
# Examples:
# IQ SOFT       -> IQSOFT
# IQ-SOFT       -> IQSOFT
# Golden Duck   -> GOLDENDUCK
#
# Myanmar characters are preserved.
# =========================================================

all_sales["Description_Clean"] = (
    all_sales["Description"]
    .astype("string")
    .str.upper()
    .str.strip()
    .str.replace(r"[^\w]", "", regex=True)
    .str.replace("_", "", regex=False)
)


# =========================================================
# STEP 3: USE ONLY EXISTING GROUP DATA TO LEARN PATTERNS
# =========================================================

known_group_data = (
    all_sales.loc[
        all_sales["Group"].notna()
        & all_sales["Description_Clean"].notna()
        & (all_sales["Description_Clean"] != ""),
        ["Description_Clean", "Group"]
    ]
    .drop_duplicates()
)


# =========================================================
# STEP 4: COUNT HOW MANY GROUPS EACH DESCRIPTION HAS
# =========================================================

description_group_count = (
    known_group_data
    .groupby("Description_Clean")["Group"]
    .nunique()
)


# =========================================================
# SITUATION 1: SAFE DESCRIPTION
#
# Only ONE known Group
#
# Example:
# BEEBEE -> LADY
#
# Therefore:
# BEEBEE + <NA> -> LADY
# =========================================================

safe_descriptions = (
    description_group_count[
        description_group_count == 1
    ]
    .index
)


safe_group_map = (
    known_group_data[
        known_group_data["Description_Clean"]
        .isin(safe_descriptions)
    ]
    .drop_duplicates("Description_Clean")
    .set_index("Description_Clean")["Group"]
)


# =========================================================
# SITUATION 2: UNSAFE DESCRIPTION
#
# More than ONE known Group
#
# Example:
# ABWALK -> MEN
# ABWALK -> LADY
#
# Therefore:
# ABWALK + <NA> -> KEEP <NA>
# =========================================================

unsafe_descriptions = (
    description_group_count[
        description_group_count > 1
    ]
    .index
)


# =========================================================
# STEP 5: FILL ONLY SAFE MISSING GROUPS
# =========================================================

missing_mask = all_sales["Group"].isna()

all_sales.loc[
    missing_mask,
    "Group"
] = (
    all_sales.loc[
        missing_mask,
        "Description_Clean"
    ]
    .map(safe_group_map)
)


# =========================================================
# STEP 6: COUNT AFTER FILLING
# =========================================================

missing_after = (
    all_sales.loc[
        all_sales["Group"].isna(),
        "Stock Code"
    ]
    .nunique()
)

group_generated = missing_before - missing_after


# =========================================================
# STEP 7: PRODUCT LEVEL RESULT
# =========================================================

print("\n========== MISSING GROUP FILLING RESULT ==========")

print(f"Total Products               : {total_products}")
print(f"Missing Before Filling       : {missing_before}")
print(f"Group Generated              : {group_generated}")
print(f"Missing After Filling        : {missing_after}")


# =========================================================
# STEP 8: DESCRIPTION PATTERN RESULT
# =========================================================

total_descriptions = all_sales["Description_Clean"].nunique()

safe_description_count = len(safe_descriptions)
unsafe_description_count = len(unsafe_descriptions)


print("\n========== DESCRIPTION GROUP PATTERN ==========")

print(f"Total Clean Descriptions     : {total_descriptions}")
print(f"Safe Single-Group Pattern    : {safe_description_count}")
print(f"Unsafe Multi-Group Pattern   : {unsafe_description_count}")


# =========================================================
# STEP 9: SHOW SAFE DESCRIPTION -> GROUP RULES
# =========================================================

safe_pattern_table = (
    safe_group_map
    .reset_index()
    .rename(columns={"Group": "Generated_Group"})
    .sort_values("Description_Clean")
)


print("\n========== SAFE DESCRIPTION -> GROUP RULE ==========")

print(
    safe_pattern_table
    .to_string(index=False)
)


# =========================================================
# STEP 10: SHOW UNSAFE DESCRIPTION PATTERNS
# =========================================================

unsafe_pattern_table = (
    known_group_data[
        known_group_data["Description_Clean"]
        .isin(unsafe_descriptions)
    ]
    .groupby("Description_Clean")["Group"]
    .apply(lambda x: ", ".join(sorted(x.unique())))
    .reset_index(name="Possible_Groups")
    .sort_values("Description_Clean")
)


print("\n========== UNSAFE DESCRIPTION -> MULTIPLE GROUPS ==========")

print(
    unsafe_pattern_table
    .to_string(index=False)
)


# =========================================================
# STEP 11: FINAL DESCRIPTION + GROUP SUMMARY
# =========================================================

description_summary = (
    all_sales[
        ["Stock Code", "Description",
         "Description_Clean", "Group"]
    ]
    .drop_duplicates()
    .groupby(
        ["Description", "Description_Clean", "Group"],
        dropna=False
    )
    .agg(
        Product_Count=("Stock Code", "nunique")
    )
    .reset_index()
    .sort_values(
        ["Description_Clean", "Group", "Product_Count"],
        ascending=[True, True, False]
    )
)


print("\n========== DESCRIPTION + GROUP SUMMARY AFTER FILLING ==========")

print(
    description_summary
    .to_string(index=False)
)

========== MISSING GROUP FILLING RESULT ==========
Total Products               : 1196
Missing Before Filling       : 677
Group Generated              : 228
Missing After Filling        : 449

========== DESCRIPTION GROUP PATTERN ==========
Total Clean Descriptions     : 294
Safe Single-Group Pattern    : 146
Unsafe Multi-Group Pattern   : 25

========== SAFE DESCRIPTION -> GROUP RULE ==========
 Description_Clean Generated_Group
              9TO5            LADY
         AANDFICTH             MEN
          ABWALK23           CHILD
          ABWALKER           CHILD
            ABWALL             MEN
              ADDA             MEN
            AFITCH             MEN
            BEEBEE            LADY
             BELLA            LADY
         BLUECAMEL             MEN
          BRAZLIAN            LADY
            CHANEL            LADY
           CHANNEL            LADY
       CHINABOOTမစ             MEN
           CLASSIC            LADY
           CONFORM            LADY
             CROCS           CHILD
           DOUBLED           CHILD
             ELISA            LADY
  FASHIONCHILDSHOE           CHILD
              FEAD            LADY
           FITTLOP            LADY
        FJFOOTWEAR             MEN
           FLOWERS            LADY
          FOOTNIKE             MEN
          FRESHYON            LADY
              FROG            LADY
            GAMBOL             MEN
             GIFTS           CHILD
        GOLDENDUCK            LADY
            GOODDY            LADY
          GRANDEUR             MEN
         HAPPYBABY           CHILD
             HORSE             MEN
              IMMI            LADY
            IQSOFT             MEN
            JABBIT            SOCK
          JANAKORN            LADY
             JASSH             MEN
             JASSY             MEN
            JIBBIT       ASSEORIES
        JOHNMARTAN             MEN
         JYLANDJYL            LADY
                K2           CHILD
              KING            SOCK
          KMCRUSHY             MEN
            KONIKA            LADY
          KULLANIT            BABY
            LABUBU           CHILD
              LAVA            LADY
             LOLLA            LADY
              LOVE           CHILD
             MAGIE           CHILD
             MALDI             MEN
            MALDNI             MEN
             MALEE            LADY
          MALESHOE           CHILD
         MALESHOES           CHILD
            MARTEN             MEN
            MASCOT            LADY
            MISTAR             MEN
               MIU            LADY
            MIUMIU            LADY
           MIXSTAR           CHILD
            MOOCHU            LADY
            MQUEEN            LADY
             MUZZE            LADY
           NESSTAR           CHILD
           NEWSTAR            LADY
             NILIN            LADY
            ORCHID            LADY
        PADANABLUE            LADY
             PENNE            LADY
           PLAYBOY             MEN
              POLA           CHILD
              PUMA            SOCK
            QSWEET            LADY
        RUBBERSTAR             MEN
               RVW            LADY
              SALE             MEN
    SHOESHINEWIPES            SOCK
            SHOWER             MEN
         SHOWERCHJ             MEN
       SHWENANNSAN            LADY
    SHWENANSANကလအဖ           CHILD
     SHWENANSANခငဖ            LADY
      SHWENANSANမဖ            LADY
SHWENANSANလယသဖOVER            LADY
 SHWENANSANလယသဖပမန            LADY
            SIAEKR             MEN
             SISCO            LADY
                SM             MEN
              SMIL            LADY
             SMILE            LADY
 SNEAKERSHINEWIPES            SOCK
              SOCK            SOCK
             SOCKS            SOCK
            SPIDER           CHILD
            SPRING            LADY
           STALKER             MEN
         STEVENSAM            LADY
           STICKER            LADY
           STORWOR            LADY
            SUZUKI            LADY
         THAISTYLE             MEN
            TOPONE            LADY
                U2           SHOES
            VRKIDS           CHILD
         WILDHORSE             MEN
                X3            SOCK
          XLNYLMEL            LADY
             YEEZI             MEN
               YES           CHILD
        ZENITHCLUB             MEN
              ကကနက             MEN
          ကကနကOVER             MEN
            ကကနကတပ             MEN
             ကကနကလ           CHILD
           ကကနမကတပ            LADY
            ကကနမသရ            LADY
               ကငဖ             MEN
              ကငဘတ             MEN
              ကလကက           CHILD
             ကလကသင           CHILD
             ခနခနလ            LADY
               ဂငထ           CHILD
           ငကငနစကင             MEN
              ဆငကယ             MEN
            ဆငခကကင             MEN
              ဆငပက            LADY
              ပငလမ            LADY
             ပနသစခ           CHILD
              ဖကငထ            LADY
              ဖဂငထ            LADY
                မစ            LADY
               မလင           CHILD
              ယနဖက             MEN
              ယနဖမ            LADY
             ရနနဆန           CHILD
          ဝပလခနစကင             MEN
             သစခပတ            LADY
           သစခဘတပတ           CHILD
            သစခဥခန            LADY
               အနစ             MEN
            ဧရ၀ဏဆင             MEN
              ၀ငလက           CHILD

========== UNSAFE DESCRIPTION -> MULTIPLE GROUPS ==========
Description_Clean        Possible_Groups
           ABWALK       CHILD, LADY, MEN
           ADIDAS             LADY, SOCK
          CRYSTAL             BABY, LADY
             EDDY       CHILD, LADY, MEN
              EVA            BABY, CHILD
          FASHION       CHILD, LADY, MEN
         FOOTNIKS             CHILD, MEN
         GOVYSOFT             CHILD, MEN
            GUCCI              LADY, MEN
             GUCI       CHILD, LADY, MEN
           HUMMER             CHILD, MEN
             KITO              LADY, MEN
             LILY            CHILD, LADY
            LOUFU            CHILD, LADY
            LUOFU BABY, CHILD, LADY, MEN
          MALDINI             CHILD, MEN
        MARCOPONY            CHILD, LADY
           MARINA            CHILD, LADY
             NIKE             LADY, SOCK
        PANDABLUE             CHILD, MEN
           PINNIP              LADY, MEN
             SHOE             CHILD, MEN
       SHWENANSAN              LADY, MEN
            SPORT             CHILD, MEN
              သစခ            CHILD, LADY

========== DESCRIPTION + GROUP SUMMARY AFTER FILLING ==========
                  Description  Description_Clean     Group  Product_Count
                          999                999      <NA>              1
                         9TO5               9TO5      LADY              2
                        9 TO5               9TO5      LADY              1
                    AANDFICTH          AANDFICTH       MEN              1
                      AB WALK             ABWALK     CHILD              6
                       ABWALK             ABWALK     CHILD              1
                      AB WALK             ABWALK      LADY              8
                       ABWALK             ABWALK      LADY              1
                      AB WALK             ABWALK       MEN              8
                       ABWALK             ABWALK       MEN              1
                      AB WALK             ABWALK      <NA>             24
                       ABWALK             ABWALK      <NA>              4
                    AB WALK23           ABWALK23     CHILD              1
                    AB WALKER           ABWALKER     CHILD              1
                      AB WALL             ABWALL       MEN              1
                    ACE SHOES           ACESHOES      <NA>              1
                         ADDA               ADDA       MEN              2
                        ADIDA              ADIDA      <NA>              1
                       ADIDAS             ADIDAS      LADY              2
                       ADIDAS             ADIDAS      SOCK              1
                       ADIDAS             ADIDAS      <NA>              2
                     AEROSOFT           AEROSOFT      <NA>             14
                      A FITCH             AFITCH       MEN              1
                        BAOJI              BAOJI      <NA>              1
                  BAOJI SHOES         BAOJISHOES      <NA>              1
                      BEE BEE             BEEBEE      LADY              7
                        BELLA              BELLA      LADY              4
                     BELONGSE           BELONGSE      <NA>              1
                   BLUE CAMEL          BLUECAMEL       MEN              1
                   BRAZILANKT         BRAZILANKT      <NA>              1
                    BRAZILANT          BRAZILANT      <NA>              1
                     BRAZILON           BRAZILON      <NA>              1
                       BRAZIN             BRAZIN      <NA>              1
                     BRAZLIAN           BRAZLIAN      LADY              1
                     BRAZLLAN           BRAZLLAN      <NA>              2
                      CARTAGO            CARTAGO      <NA>              3
                       CHANEL             CHANEL      LADY              4
                      CHANNEL            CHANNEL      LADY              3
                       CHARMI             CHARMI      <NA>              1
          CHINA BOOT(မိုးစီး)        CHINABOOTမစ       MEN              1
                      CLASSIC            CLASSIC      LADY              1
                      CONFORM            CONFORM      LADY              1
                        CROCS              CROCS     CHILD              5
                        CROSS              CROSS      <NA>              1
                      CRYSTAL            CRYSTAL      BABY              1
                      CRYSTAL            CRYSTAL      LADY              2
                        CUFFY              CUFFY      <NA>              1
                         DIOR               DIOR      <NA>              1
                      DOUBLED            DOUBLED     CHILD              9
                   DR MARTINE          DRMARTINE      <NA>              2
                   DR.MARTINE          DRMARTINE      <NA>              1
                         EDDY               EDDY     CHILD              3
                         EDDY               EDDY      LADY              2
                         EDDY               EDDY       MEN              1
                         EDDY               EDDY      <NA>              6
                        EIISA              EIISA      <NA>              1
                        ELISA              ELISA      LADY             27
                        ELISE              ELISE      <NA>              1
                         ELSA               ELSA      <NA>              1
                          EVA                EVA      BABY              1
                          EVA                EVA     CHILD              1
                      FARTAIN            FARTAIN      <NA>              1
                 FARTIN STYLE        FARTINSTYLE      <NA>              1
                      FASHION            FASHION     CHILD              5
                      FASHION            FASHION      LADY             10
                      FASHION            FASHION       MEN              1
                      FASHION            FASHION      <NA>             23
          FASHION(CHILD SHOE)   FASHIONCHILDSHOE     CHILD              2
                FASHION MJ608       FASHIONMJ608      <NA>              1
                FASHION SHOES       FASHIONSHOES      <NA>              1
          FASHION SPORT TG300  FASHIONSPORTTG300      <NA>              1
                         FEAD               FEAD      LADY              1
                      FITTLOP            FITTLOP      LADY              1
                  FJ FOOTWEAR         FJFOOTWEAR       MEN              1
                     FJ SPORT            FJSPORT      <NA>              1
                      FLOWERS            FLOWERS      LADY              1
                      FOOTNIK            FOOTNIK      <NA>              1
                     FOOTNIKE           FOOTNIKE       MEN              1
                     FOOTNIKS           FOOTNIKS     CHILD              7
                     FOOTNIKS           FOOTNIKS       MEN              2
                    FOOT NIKS           FOOTNIKS      <NA>              6
                     FOOTNIKS           FOOTNIKS      <NA>              3
                     FOOTNILK           FOOTNILK      <NA>              6
                      FORTUNE            FORTUNE      <NA>              1
                     FRESHYON           FRESHYON      LADY              5
                         FROG               FROG      LADY              1
                        FSRAW              FSRAW      <NA>              1
                      FTTIIOD            FTTIIOD      <NA>              1
                       GAMBOL             GAMBOL       MEN              3
                     GD SHOES            GDSHOES      <NA>              1
                        GIFTS              GIFTS     CHILD              2
                     GOLDCITY           GOLDCITY      <NA>              1
                  GOLDEN DUCK         GOLDENDUCK      LADY             20
                   GOLDENDUCK         GOLDENDUCK      LADY              7
                       GOODDY             GOODDY      LADY             16
                        GOODY              GOODY      <NA>              1
                    GOVY SOFT           GOVYSOFT     CHILD              5
                    GOVY SOFT           GOVYSOFT       MEN              7
                    GOVY SOFT           GOVYSOFT      <NA>              4
                     GOVYSOFT           GOVYSOFT      <NA>              1
                     GRANDEUR           GRANDEUR       MEN              3
                        GUCCI              GUCCI      LADY              4
                        GUCCI              GUCCI       MEN              1
                        GUCCI              GUCCI      <NA>              8
                         GUCI               GUCI     CHILD              1
                         GUCI               GUCI      LADY              2
                         GUCI               GUCI       MEN              7
                         GUCI               GUCI      <NA>             21
                   HAPPY BABY          HAPPYBABY     CHILD              2
                    HAVALANAS          HAVALANAS      <NA>              1
                        HORSE              HORSE       MEN              1
                     HOTMARZZ           HOTMARZZ      <NA>              1
                       HUMMER             HUMMER     CHILD              6
                       HUMMER             HUMMER       MEN              1
                       HUMMER             HUMMER      <NA>             17
                          IMM                IMM      <NA>              1
                         IMMI               IMMI      LADY              2
                      IQ SOFT             IQSOFT       MEN              7
                       IQSOFT             IQSOFT       MEN              1
                      I SHOES             ISHOES      <NA>              1
                       JABBIT             JABBIT      SOCK              5
                      JANAGON            JANAGON      <NA>              1
                     JANAKORN           JANAKORN      LADY              2
                        JASSH              JASSH       MEN              1
                        JASSY              JASSY       MEN              3
                       JIBBIT             JIBBIT ASSEORIES              6
                      JINZUDA            JINZUDA      <NA>              1
                        JJ168              JJ168      <NA>              1
                  JOHN MARTAN         JOHNMARTAN       MEN              3
                   JOHNMARTAN         JOHNMARTAN       MEN              1
                        JUMBO              JUMBO      <NA>              1
                    JYLANDJYL          JYLANDJYL      LADY              1
                           K2                 K2     CHILD              4
                KHAING MARLAR       KHAINGMARLAR      <NA>              1
                         KING               KING      SOCK              1
                         KITO               KITO      LADY              3
                         KITO               KITO       MEN              1
                         KITO               KITO      <NA>              8
                    KM CRUSHY           KMCRUSHY       MEN              3
                     KM CUSHY            KMCUSHY      <NA>              7
                       KONIKA             KONIKA      LADY              2
                     KULLANIT           KULLANIT      BABY              5
                       KUROMI             KUROMI      <NA>              2
                       LABUBU             LABUBU     CHILD              9
                      LACOSTE            LACOSTE      <NA>              2
                         LAVA               LAVA      LADY              2
                     LAVANDAR           LAVANDAR      <NA>              1
                     LAVENDAR           LAVENDAR      <NA>              1
                         LILY               LILY     CHILD              1
                         LILY               LILY      LADY             19
                         LILY               LILY      <NA>             14
                      LIMITED            LIMITED      <NA>              1
                        LOLLA              LOLLA      LADY             35
                        LOUFO              LOUFO      <NA>              1
                        LOUFU              LOUFU     CHILD              1
                        LOUFU              LOUFU      LADY              2
                        LOUFU              LOUFU      <NA>              4
                         LOVE               LOVE     CHILD              1
                        LUOFU              LUOFU      BABY              1
                        LUOFU              LUOFU     CHILD             11
                        LUOFU              LUOFU      LADY             21
                        LUOFU              LUOFU       MEN             24
                        LUOFU              LUOFU      <NA>             30
                           LV                 LV      <NA>              1
                        MAGIE              MAGIE     CHILD              1
                        MALDI              MALDI       MEN              3
                      MALDINI            MALDINI     CHILD              4
                      MALDINI            MALDINI       MEN             15
                      MALDINI            MALDINI      <NA>             41
                       MALDNI             MALDNI       MEN              1
                        MALEE              MALEE      LADY              3
                    MALE SHOE           MALESHOE     CHILD              1
                   MALE SHOES          MALESHOES     CHILD              1
                    MARCOPONY          MARCOPONY     CHILD              4
                    MARCOPONY          MARCOPONY      LADY              2
                    MARCOPONY          MARCOPONY      <NA>              6
                   MARCO PONY          MARCOPONY      <NA>              1
                       MARINA             MARINA     CHILD              1

In [18]:
# ---------------------------------------------------------
# 3.3 CHECK STOCK CODE CONSISTENCY
# DESCRIPTION + GROUP
# ---------------------------------------------------------

stock_code_check = (
    all_sales
    .groupby("Stock Code")
    .agg(
        Description_Count=("Description", "nunique"),
        Group_Count=("Group", "nunique")
    )
    .reset_index()
)

# ---------------------------------------------------------
# STOCK CODES WITH MULTIPLE DESCRIPTIONS
# ---------------------------------------------------------

multiple_description = stock_code_check[
    stock_code_check["Description_Count"] > 1
]

# ---------------------------------------------------------
# STOCK CODES WITH MULTIPLE GROUPS
# ---------------------------------------------------------

multiple_group = stock_code_check[
    stock_code_check["Group_Count"] > 1
]

# ---------------------------------------------------------
# CHECK RESULT
# ---------------------------------------------------------

print("========== STOCK CODE CONSISTENCY CHECK ==========")

print("\nStock Codes with Multiple Descriptions:")
print(len(multiple_description))

print("\nStock Codes with Multiple Groups:")
print(len(multiple_group))

print("\nMultiple Description Sample:")
print(
    multiple_description
    .head(20)
    .to_string(index=False)
)

print("\nMultiple Group Sample:")
print(
    multiple_group
    .head(20)
    .to_string(index=False)
)

========== STOCK CODE CONSISTENCY CHECK ==========

Stock Codes with Multiple Descriptions:
0

Stock Codes with Multiple Groups:
0

Multiple Description Sample:
Empty DataFrame
Columns: [Stock Code, Description_Count, Group_Count]
Index: []

Multiple Group Sample:
Empty DataFrame
Columns: [Stock Code, Description_Count, Group_Count]
Index: []

Alarm system addition for the uploading the

In [19]:
# =========================================================
# 3.4 Claer FINAL UNIQUE DESCRIPTION NAMES
# =========================================================

final_unique_descriptions = (
    all_sales["Description_Clean"]
    .dropna()
    .loc[lambda x: x != ""]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("\n========== FINAL UNIQUE DESCRIPTION NAMES ==========")

print(f"Total Unique Descriptions : {len(final_unique_descriptions)}")

print(
    final_unique_descriptions
    .to_string(index=False)
)

========== FINAL UNIQUE DESCRIPTION NAMES ==========
Total Unique Descriptions : 294
               999
              9TO5
         AANDFICTH
            ABWALK
          ABWALK23
          ABWALKER
            ABWALL
          ACESHOES
              ADDA
             ADIDA
            ADIDAS
          AEROSOFT
            AFITCH
             BAOJI
        BAOJISHOES
            BEEBEE
             BELLA
          BELONGSE
         BLUECAMEL
        BRAZILANKT
         BRAZILANT
          BRAZILON
            BRAZIN
          BRAZLIAN
          BRAZLLAN
           CARTAGO
            CHANEL
           CHANNEL
            CHARMI
       CHINABOOTမစ
           CLASSIC
           CONFORM
             CROCS
             CROSS
           CRYSTAL
             CUFFY
              DIOR
           DOUBLED
         DRMARTINE
              EDDY
             EIISA
             ELISA
             ELISE
              ELSA
               EVA
           FARTAIN
       FARTINSTYLE
           FASHION
  FASHIONCHILDSHOE
      FASHIONMJ608
      FASHIONSHOES
 FASHIONSPORTTG300
              FEAD
           FITTLOP
        FJFOOTWEAR
           FJSPORT
           FLOWERS
           FOOTNIK
          FOOTNIKE
          FOOTNIKS
          FOOTNILK
           FORTUNE
          FRESHYON
              FROG
             FSRAW
           FTTIIOD
            GAMBOL
           GDSHOES
             GIFTS
          GOLDCITY
        GOLDENDUCK
            GOODDY
             GOODY
          GOVYSOFT
          GRANDEUR
             GUCCI
              GUCI
         HAPPYBABY
         HAVALANAS
             HORSE
          HOTMARZZ
            HUMMER
               IMM
              IMMI
            IQSOFT
            ISHOES
            JABBIT
           JANAGON
          JANAKORN
             JASSH
             JASSY
            JIBBIT
           JINZUDA
             JJ168
        JOHNMARTAN
             JUMBO
         JYLANDJYL
                K2
      KHAINGMARLAR
              KING
              KITO
          KMCRUSHY
           KMCUSHY
            KONIKA
          KULLANIT
            KUROMI
            LABUBU
           LACOSTE
              LAVA
          LAVANDAR
          LAVENDAR
              LILY
           LIMITED
             LOLLA
             LOUFO
             LOUFU
              LOVE
             LUOFU
                LV
             MAGIE
             MALDI
           MALDINI
            MALDNI
             MALEE
          MALESHOE
         MALESHOES
         MARCOPONY
            MARINA
            MARTEN
           MARTINE
            MASCOT
           MCQUEEN
            MEIQIN
       MEMBERSMENU
             METOO
           MINICAT
            MISTAR
               MIU
            MIUMIU
           MIXSTAR
            MOOCHU
           MOOCHUU
            MQUEEN
            MSMILE
             MUZZE
           NESSTAR
           NEWSTAR
              NICE
              NIKE
             NILIN
      NISASHOESF84
           NSASHOE
          NSASHOES
             OMEGA
            ORCHID
            ORIPES
        PADANABLUE
         PANDABLUE
              PEME
             PENNE
            PINNIP
           PLAYBOY
               PMP
              POLA
              PUMA
            QSWEET
             QTRAL
            RABBIT
           RAGAZZO
           RAINBOW
                RD
             RIDER
             RIOME
        RISINGSTAR
            ROSITA
        RUBBERSTAR
               RUN
           RUNFAST
               RVW
              SALE
           SENSINI
             SHDTR
            SHELAY
              SHOE
             SHOES
    SHOESHINEWIPES
            SHOWER
         SHOWERCHJ
       SHWENANNSAN
        SHWENANSAN
    SHWENANSANကလအဖ
     SHWENANSANခငဖ
      SHWENANSANမဖ
SHWENANSANလယသဖOVER
 SHWENANSANလယသဖပမန
            SIAEKR
             SISCO
                SM
        SMFOOTWARE
              SMIL
             SMILE
       SMILEKUROMI
 SNEAKERSHINEWIPES
              SNOW
              SOCK
             SOCKS
          SOGOLITE
            SPARTS
            SPIDER
             SPORT
            SPRING
           STALKER
         STEVENSAM
           STICKER
           STORWOR
             STRDJ
               SUP
            SUZUKI
             SWEET
        SWEETHAPPY
         THAISTYLE
          THITKHAW
            TOMATO
            TOPONE
          TOTALAND
                U2
             VENUS
           VERSACE
          VICTORIA
            VRKIDS
            WALKER
              WALL
            WARING
         WATERFISH
          WELLNINE
         WILDHORSE
            WINKKI
      WINKKIKT8439
        WORLDSWEET
                X3
          XLNYLMEL
             YEEZI
        YEEZYSLIDE
               YES
        ZENITHCLUB
              ကကနက
          ကကနကOVER
            ကကနကတပ
             ကကနကလ
              ကကနမ
           ကကနမကတပ
            ကကနမသရ
             ကငထမစ
               ကငဖ
              ကငဘတ
              ကနမရ
              ကလကက
             ကလကသင
             ကလမစစ
             ခညပမစ
             ခနခနလ
               ဂငထ
           ငကငနစကင
              ဆငကယ
            ဆငခကကင
              ဆငပက
              ထပပတ
              ပငလက
              ပငလမ
             ပနသစခ
              ဖကငထ
              ဖဂငထ
                မခ
                မစ
             မစကငထ
             မစဂငထ
            မစမခညပ
               မလင
              ယနဖက
              ယနဖမ
             ရနနဆန
          ဝပလခနစကင
               သစခ
            သစခတပထ
             သစခပတ
            သစခပလန
           သစခဘတပတ
            သစခဥခန
                သရ
                အန
               အနစ
              အသကပ
            ဧရ၀ဏဆင
              ၀ငလက

In [20]:
# =========================================================
# EXPORT UNIQUE DESCRIPTION LIST TO EXCEL
# =========================================================

description_group = (
    all_sales[
        ["Description_Clean", "Group"]
    ]
    .drop_duplicates()
    .sort_values("Description_Clean")
    .reset_index(drop=True)
)

description_group.to_excel(
    "description_group_mapping.xlsx",
    index=False
)

print("File created: description_group_mapping.xlsx")
print("Total rows:", len(description_group))

File created: description_group_mapping.xlsx
Total rows: 349

In [21]:
# =========================================================
# STEP 3.7 — CHECK PRODUCT MASTER COLUMNS
# =========================================================

print("========== PRODUCT MASTER COLUMNS ==========")

for col in product_master.columns:
    print(col)

========== PRODUCT MASTER COLUMNS ==========
Branch
Stock Code
Description
Group
Selling Price
Buying Price
On Hand Qty
In Sale
In Inventory
In Purchase

In [22]:
# ==============================================
# CHECK WHICH SHOP / BRANCH THE DATA COMES FROM
# ==============================================

print("product_master columns:")
print(product_master.columns.tolist())

print("\nPossible shop/branch columns:")

for col in product_master.columns:
    if any(word in col.lower() for word in ["shop", "branch", "store", "location"]):
        print(col)

product_master columns:
['Branch', 'Stock Code', 'Description', 'Group', 'Selling Price', 'Buying Price', 'On Hand Qty', 'In Sale', 'In Inventory', 'In Purchase']

Possible shop/branch columns:
Branch

In [23]:
# =========================================================
# STEP 3.7.1 — CLEAN SELLING PRICE
# =========================================================

product_master["Selling Price"] = pd.to_numeric(
    product_master["Selling Price"],
    errors="coerce"
)

print("========== SELLING PRICE CHECK ==========")

print("Products:", len(product_master))
print("Missing Selling Price:", product_master["Selling Price"].isna().sum())

print("\nPrice Statistics:")
print(product_master["Selling Price"].describe().round(0).astype(int))

========== SELLING PRICE CHECK ==========
Products: 1320
Missing Selling Price: 677

Price Statistics:
count      643
mean     28112
std      15727
min       1500
25%      14500
50%      28500
75%      39500
max      95000
Name: Selling Price, dtype: int64

step( 3.7.2 )If we don't know the current selling price, use the most recent price that Ashley actually sold that product for."
And sale.csv contains:
Date	Stock Code	Selling Price
2026-05-01	A002	28,000
2026-06-01	A002	30,000


The code takes the latest price, so:
A002 → 30,000
Final result:
Stock Code	Selling Price
A001	25,000
A002	30,000

In [24]:
# ==========================================================
# STEP 3.7.2 — RECOVER MISSING SELLING PRICE FROM SALE
# ==========================================================

# Make sure sale selling price is numeric
sale["Selling Price"] = pd.to_numeric(
    sale["Selling Price"],
    errors="coerce"
)

# Keep only Ashley
ashley_sale = sale[
    sale["Branch"].astype(str).str.strip().str.lower() == "ashley"
].copy()

# Convert date
ashley_sale["Date"] = pd.to_datetime(
    ashley_sale["Date"],
    errors="coerce"
)

# Sort so latest record is last
ashley_sale = ashley_sale.sort_values("Date")

# Get latest valid selling price for each Stock Code
latest_sale_price = (
    ashley_sale
    .dropna(subset=["Selling Price"])
    .drop_duplicates(subset="Stock Code", keep="last")
    [["Stock Code", "Selling Price"]]
    .rename(columns={"Selling Price": "Sale Selling Price"})
)

# Merge with product master
product_master = product_master.merge(
    latest_sale_price,
    on="Stock Code",
    how="left"
)

# Count before filling
missing_before = product_master["Selling Price"].isna().sum()

# Fill ONLY missing inventory selling prices
product_master["Selling Price"] = (
    product_master["Selling Price"]
    .fillna(product_master["Sale Selling Price"])
)

# Count after filling
missing_after = product_master["Selling Price"].isna().sum()

print("========== SELLING PRICE RECOVERY ==========")

print("Branch: Ashley")
print("Missing Before:", missing_before)
print("Recovered From Sale:", missing_before - missing_after)
print("Still Missing:", missing_after)

========== SELLING PRICE RECOVERY ==========
Branch: Ashley
Missing Before: 677
Recovered From Sale: 677
Still Missing: 0

In [25]:
# ==========================================================
# STEP 3.7.3 — FINAL SELLING PRICE VALIDATION
# ==========================================================

print("========== FINAL SELLING PRICE CHECK ==========")

print("Total Products:", len(product_master))
print("Missing Price:", product_master["Selling Price"].isna().sum())
print("Zero Price:", (product_master["Selling Price"] == 0).sum())
print("Negative Price:", (product_master["Selling Price"] < 0).sum())

print("\nFinal Price Statistics:")
print(product_master["Selling Price"].describe().round(0).astype(int))

========== FINAL SELLING PRICE CHECK ==========
Total Products: 1320
Missing Price: 0
Zero Price: 0
Negative Price: 0

Final Price Statistics:
count      1320
mean      27128
std       15245
min        1500
25%       14500
50%       25500
75%       38000
max      137500
Name: Selling Price, dtype: int64

Step 3.7.4 — Create Price Range
Because your goal is to understand the general product price levels, we can use the 25th and 75th percentiles already found in your real Ashley data:
- Low: ≤ 14,500
- Mid: 14,501–38,000
- High: > 38,000
Run:

In [26]:
# ==========================================================
# STEP 3.7.4 — CREATE PRICE RANGE
# ==========================================================

def create_price_range(price):

    if price <= 14500:
        return "Low"

    elif price <= 38000:
        return "Mid"

    else:
        return "High"


product_master["Price Range"] = (
    product_master["Selling Price"]
    .apply(create_price_range)
)


print("========== PRICE RANGE ==========")

print(
    product_master["Price Range"]
    .value_counts()
)

print("\nPrice Range Summary:")

print(
    product_master.groupby("Price Range")["Selling Price"]
    .agg(["count", "min", "mean", "max"])
    .round(0)
)

========== PRICE RANGE ==========
Price Range
Mid     665
Low     336
High    319
Name: count, dtype: int64

Price Range Summary:
             count      min     mean       max
Price Range
High           319  38100.0  47736.0  137500.0
Low            336   1500.0   9204.0   14500.0
Mid            665  14800.0  26299.0   38000.0

Low     = 336 products   (1,500 – 14,500)
Mid     = 665 products   (14,800 – 38,000)
High    = 319 products   (38,100 – 137,500)

Total   = 1,320 products
So about half of the Ashley products are in the Mid price range.

Step 4 — ABC Analysis, using Ashley historical sales and Net Amount to identify:
A = highest sales-value contribution
B = medium contribution
C = lowest contribution
Then we can connect ABC Class + Price
Step 4.1 — Prepare Ashley Sales for ABC Analysis
We will use Net Amount because ABC analysis should measure how much sales value each product contributes.

In [27]:
# ==========================================================
# STEP 4.1 — PREPARE SALES DATA FOR ABC ANALYSIS
# ==========================================================

# Keep Ashley only
abc_sale = sale[
    sale["Branch"].astype(str).str.strip().str.lower() == "ashley"
].copy()

# Convert important columns to numeric
abc_sale["Qty"] = pd.to_numeric(
    abc_sale["Qty"],
    errors="coerce"
)

abc_sale["Net Amount"] = pd.to_numeric(
    abc_sale["Net Amount"],
    errors="coerce"
)

# Convert Date
abc_sale["Date"] = pd.to_datetime(
    abc_sale["Date"],
    errors="coerce"
)

# Remove rows that cannot be used for ABC
abc_sale = abc_sale.dropna(
    subset=["Stock Code", "Net Amount"]
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== ABC SALES DATA CHECK ==========")

print("Branch: Ashley")
print("Sales Rows:", len(abc_sale))

print("\nDate Range:")
print("First Date:", abc_sale["Date"].min())
print("Last Date:", abc_sale["Date"].max())

print("\nNet Amount Check:")
print("Missing:", abc_sale["Net Amount"].isna().sum())
print("Zero:", (abc_sale["Net Amount"] == 0).sum())
print("Negative:", (abc_sale["Net Amount"] < 0).sum())

print("\nTotal Sales Value:")
print(round(abc_sale["Net Amount"].sum(), 0))

========== ABC SALES DATA CHECK ==========
Branch: Ashley
Sales Rows: 9459

Date Range:
First Date: 2025-02-09 00:00:00
Last Date: 2026-09-04 00:00:00

Net Amount Check:
Missing: 0
Zero: 2
Negative: 0

Total Sales Value:
231582942.0

The 2 zero-value rows contribute nothing to ABC sales value, so we can exclude them from the ABC calculation.

In [28]:
# ==========================================================
# STEP 4.2 — CALCULATE SALES PERFORMANCE BY PRODUCT
# ==========================================================

# Keep transactions with positive sales value
abc_valid = abc_sale[
    abc_sale["Net Amount"] > 0
].copy()

# Calculate total performance for each product
abc_product = (
    abc_valid
    .groupby("Stock Code")
    .agg(
        Total_Qty_Sold=("Qty", "sum"),
        Total_Sales_Value=("Net Amount", "sum"),
        Sales_Transactions=("Stock Code", "size")
    )
    .reset_index()
)

# Sort highest sales value first
abc_product = abc_product.sort_values(
    "Total_Sales_Value",
    ascending=False
).reset_index(drop=True)


# ==========================================================
# CHECK RESULT
# ==========================================================

print("========== PRODUCT SALES PERFORMANCE ==========")

print("Products Sold:", len(abc_product))

print("\nTotal Quantity Sold:")
print(round(abc_product["Total_Qty_Sold"].sum(), 0))

print("\nTotal Sales Value:")
print(round(abc_product["Total_Sales_Value"].sum(), 0))

print("\nTop 10 Products by Sales Value:")

print(
    abc_product.head(10)
    .to_string(index=False)
)
#Goal Goal: find how much each product actually contributes to Ashley's sales.

========== PRODUCT SALES PERFORMANCE ==========
Products Sold: 1196

Total Quantity Sold:
10719.0

Total Sales Value:
231582942.0

Top 10 Products by Sales Value:
Stock Code  Total_Qty_Sold  Total_Sales_Value  Sales_Transactions
     F2326           133.0          4176450.0                 119
    SHOWER           379.0          3502000.0                 269
        SM           131.0          3298350.0                 120
  E6230E01            75.0          3112500.0                  71
     EDD35           188.0          2925100.0                 141
    LF2326           111.0          2781300.0                  57
     E6217            68.0          2510800.0                  54
     EDD45           163.0          2475350.0                  76
     WR888            85.0          2217100.0                  82
    000139           125.0          2029500.0                  84

#Reminder -Remember, your Product Master has 1,320 products, but only 1,196 products had sales during the period. So 124 products had no sales in this sales history. We should keep that information because it will be important later for purchasing decisions.
Step 4.3 — Calculate Sales Contribution %

In [29]:
# ==========================================================
# STEP 4.3 — CALCULATE SALES CONTRIBUTION
# ==========================================================

# Total sales value
total_sales_value = abc_product["Total_Sales_Value"].sum()

# Contribution of each product to total sales
abc_product["Sales_Contribution_%"] = (
    abc_product["Total_Sales_Value"]
    / total_sales_value
    * 100
)

# Cumulative contribution
abc_product["Cumulative_%"] = (
    abc_product["Sales_Contribution_%"].cumsum()
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== SALES CONTRIBUTION ==========")

print("Total Products Sold:", len(abc_product))
print("Total Sales Value:", round(total_sales_value, 0))

print("\nTop 15 Products:")

print(
    abc_product[
        [
            "Stock Code",
            "Total_Qty_Sold",
            "Total_Sales_Value",
            "Sales_Contribution_%",
            "Cumulative_%"
        ]
    ]
    .head(15)
    .round(2)
    .to_string(index=False)
)

print("\nFinal Cumulative %:")
print(round(abc_product["Cumulative_%"].iloc[-1], 2))

========== SALES CONTRIBUTION ==========
Total Products Sold: 1196
Total Sales Value: 231582942.0

Top 15 Products:
Stock Code  Total_Qty_Sold  Total_Sales_Value  Sales_Contribution_%  Cumulative_%
     F2326           133.0          4176450.0                  1.80          1.80
    SHOWER           379.0          3502000.0                  1.51          3.32
        SM           131.0          3298350.0                  1.42          4.74
  E6230E01            75.0          3112500.0                  1.34          6.08
     EDD35           188.0          2925100.0                  1.26          7.35
    LF2326           111.0          2781300.0                  1.20          8.55
     E6217            68.0          2510800.0                  1.08          9.63
     EDD45           163.0          2475350.0                  1.07         10.70
     WR888            85.0          2217100.0                  0.96         11.66
    000139           125.0          2029500.0                  0.88         12.53
      F2KU           121.0          1758300.0                  0.76         13.29
    A01617           135.0          1733200.0                  0.75         14.04
  E6213E32            42.0          1680000.0                  0.73         14.77
      KKNM            73.0          1578100.0                  0.68         15.45
BLUE CAMEL           108.0          1565000.0                  0.68         16.13

Final Cumulative %:
100.0

Step 4 — ABC Analysis, using Ashley historical sales and Net Amount to identify:
A = highest sales-value contribution
B = medium contribution
C = lowest contribution
Then we can connect ABC Class + Price
Step 4.1 — Prepare Ashley Sales for ABC Analysis
We will use Net Amount because ABC analysis should measure how much sales value each product contributes.

In [30]:
# ==========================================================
# STEP 4.4 — ASSIGN ABC CLASS
# ==========================================================

# Use cumulative percentage BEFORE each product
previous_cumulative = (
    abc_product["Cumulative_%"]
    - abc_product["Sales_Contribution_%"]
)

# Assign ABC class
abc_product["ABC_Class"] = np.select(
    [
        previous_cumulative < 80,
        previous_cumulative < 95
    ],
    [
        "A",
        "B"
    ],
    default="C"
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== ABC CLASSIFICATION ==========")

print("\nNumber of Products:")
print(
    abc_product["ABC_Class"]
    .value_counts()
    .sort_index()
)

print("\nABC Summary:")

abc_summary = (
    abc_product
    .groupby("ABC_Class")
    .agg(
        Products=("Stock Code", "count"),
        Total_Qty=("Total_Qty_Sold", "sum"),
        Sales_Value=("Total_Sales_Value", "sum")
    )
)

abc_summary["Sales_%"] = (
    abc_summary["Sales_Value"]
    / abc_product["Total_Sales_Value"].sum()
    * 100
)

abc_summary["Product_%"] = (
    abc_summary["Products"]
    / len(abc_product)
    * 100
)

print(
    abc_summary
    .round(2)
    .to_string()
)
# ----------------------------------------------------------
# ADD TOTAL PRODUCTS + NO SALES PRODUCTS
# ----------------------------------------------------------

total_products = len(product_master)
products_with_sales = len(abc_product)
no_sales_products = total_products - products_with_sales

print("\nTotal Products from Product Master:", total_products)
print("N - No Sales:", no_sales_products)

========== ABC CLASSIFICATION ==========

Number of Products:
ABC_Class
A    468
B    358
C    370
Name: count, dtype: int64

ABC Summary:
           Products  Total_Qty  Sales_Value  Sales_%  Product_%
ABC_Class
A               468     7968.0  185377892.0    80.05      39.13
B               358     1925.0   34661950.0    14.97      29.93
C               370      826.0   11543100.0     4.98      30.94

Total Products from Product Master: 1320
N - No Sales: 124

Class	Meaning	Your result
A	Most important / biggest sales contributors	468 products generate 80.05% of sales
B	Medium contributors	358 products generate 14.97% of sales
C	Small contributors	370 products generate only 4.98% of sales

A products → products responsible for roughly the first 80% of Ashley's sales value → very important to monitor for purchasing.
B products → next roughly 15% → medium importance.
C products → remaining roughly 5% → individually contribute relatively little sales value
*39.13% of your products (A class) generate about 80% of total sales value.
the Product Master contains 1,320 products, so we still have 124 products with no positive sales. We should not call those C products, because C means they did sell, but contributed little sales value. Give the 124 products a separate class such as N = No Sales.
Step 4.5 — Merge ABC into Product Master

In [31]:
# ==========================================================
# STEP 4.5 — MERGE ABC RESULT INTO PRODUCT MASTER
# ==========================================================

# Keep ABC information needed for Product Master
abc_merge = abc_product[
    [
        "Stock Code",
        "Total_Qty_Sold",
        "Total_Sales_Value",
        "Sales_Transactions",
        "Sales_Contribution_%",
        "ABC_Class"
    ]
].copy()

# Merge ABC result
product_master = product_master.merge(
    abc_merge,
    on="Stock Code",
    how="left"
)

# ----------------------------------------------------------
# PRODUCTS WITH NO SALES
# ----------------------------------------------------------

product_master["ABC_Class"] = (
    product_master["ABC_Class"]
    .fillna("N")
)

# No-sales products should have 0 sales values
sales_columns = [
    "Total_Qty_Sold",
    "Total_Sales_Value",
    "Sales_Transactions",
    "Sales_Contribution_%"
]

product_master[sales_columns] = (
    product_master[sales_columns]
    .fillna(0)
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== PRODUCT MASTER + ABC ==========")

print("Total Products:", len(product_master))

print("\nABC Classes:")
print(
    product_master["ABC_Class"]
    .value_counts()
    .sort_index()
)

print("\nCheck Total:")
print(
    product_master["ABC_Class"]
    .value_counts()
    .sum()
)

========== PRODUCT MASTER + ABC ==========
Total Products: 1320

ABC Classes:
ABC_Class
A    468
B    358
C    370
N    124
Name: count, dtype: int64

Check Total:
1320

Now continue to Step 4.6 — ABC + Price Range Analysis. This will show whether A, B, C, and No-Sales products are mainly Low, Mid, or High priced.

In [32]:
# ==========================================================
# STEP 4.6 — ABC CLASS + PRICE RANGE ANALYSIS
# ==========================================================

abc_price = pd.crosstab(
    product_master["ABC_Class"],
    product_master["Price Range"]
)

# Put columns in clear order
abc_price = abc_price.reindex(
    columns=["Low", "Mid", "High"],
    fill_value=0
)

# Add total
abc_price["Total"] = abc_price.sum(axis=1)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== ABC + PRICE RANGE ==========")

print(abc_price)

print("\n========== PERCENTAGE WITHIN EACH ABC CLASS ==========")

abc_price_percent = pd.crosstab(
    product_master["ABC_Class"],
    product_master["Price Range"],
    normalize="index"
) * 100

abc_price_percent = abc_price_percent.reindex(
    columns=["Low", "Mid", "High"],
    fill_value=0
)

print(
    abc_price_percent
    .round(1).astype(str) + "%"
)

========== ABC + PRICE RANGE ==========
Price Range  Low  Mid  High  Total
ABC_Class
A             61  233   174    468
B             82  218    58    358
C            155  175    40    370
N             38   39    47    124

========== PERCENTAGE WITHIN EACH ABC CLASS ==========
Price Range    Low    Mid   High
ABC_Class
A            13.0%  49.8%  37.2%
B            22.9%  60.9%  16.2%
C            41.9%  47.3%  10.8%
N            30.6%  31.5%  37.9%

Code → Expected Output → Explanation → Goal
Your current result tells us that A products are mostly Mid (49.79%) and High (37.18%), while C products have a much larger Low-price share (41.89%). Now we should connect ABC performance with current stock.
Step

A products are mainly Mid and High priced:

Insight- “Most of my important sales-contributing products are in the Mid and High price ranges.”
Step 4.7 — Connect ABC with Current Inventory
First, clean On Hand Qty and see current stock by ABC class.

In [33]:
# ==========================================================
# STEP 4.7 — ABC + CURRENT INVENTORY
# ==========================================================

# Clean On Hand Qty
product_master["On Hand Qty"] = pd.to_numeric(
    product_master["On Hand Qty"],
    errors="coerce"
)

# Products without inventory record = 0 current stock
product_master["On Hand Qty"] = (
    product_master["On Hand Qty"]
    .fillna(0)
)

# ----------------------------------------------------------
# CREATE INVENTORY SUMMARY BY ABC CLASS
# ----------------------------------------------------------

abc_inventory = (
    product_master
    .groupby("ABC_Class")
    .agg(
        Products=("Stock Code", "count"),
        Total_Stock=("On Hand Qty", "sum"),
        Average_Stock=("On Hand Qty", "mean"),
        Out_of_Stock=("On Hand Qty", lambda x: (x <= 0).sum())
    )
)

abc_inventory["Average_Stock"] = (
    abc_inventory["Average_Stock"].round(2)
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== ABC + CURRENT INVENTORY ==========")

print(abc_inventory)

print("\nTotal Current Stock:")
print(round(product_master["On Hand Qty"].sum(), 0))

========== ABC + CURRENT INVENTORY ==========
           Products  Total_Stock  Average_Stock  Out_of_Stock
ABC_Class
A               468       2051.0           4.38           242
B               358        875.0           2.44           208
C               370        917.0           2.48           230
N               124        639.0           5.15             0

Total Current Stock:
4482.0

The biggest thing to investigate is A products: 242 of 468 A products show zero stock. Since A products generated about 80% of historical sales value, these are strong candidates for purchasing attention. But we should not automatically say “buy them” yet—we need to see each product's sales and stock.
Step 4.8 — Find A Products That Are Out of Stock

In [34]:
# ==========================================================
# STEP 4.8 — FIND A PRODUCTS THAT ARE OUT OF STOCK
# ==========================================================

a_out_of_stock = product_master[
    (product_master["ABC_Class"] == "A") &
    (product_master["On Hand Qty"] <= 0)
].copy()

# Sort by highest historical sales value
a_out_of_stock = a_out_of_stock.sort_values(
    "Total_Sales_Value",
    ascending=False
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== A PRODUCTS — OUT OF STOCK ==========")

print("Number of Products:", len(a_out_of_stock))

print("\nTop 20 Products Needing Attention:")

print(
    a_out_of_stock[
        [
            "Stock Code",
            "Description",
            "Price Range",
            "Selling Price",
            "Total_Qty_Sold",
            "Total_Sales_Value",
            "On Hand Qty"
        ]
    ]
    .head(20)
    .round(2)
    .to_string(index=False)
)

========== A PRODUCTS — OUT OF STOCK ==========
Number of Products: 242

Top 20 Products Needing Attention:
Stock Code  Description Price Range  Selling Price  Total_Qty_Sold  Total_Sales_Value  On Hand Qty
     F2326        Luofu         Mid        34500.0           133.0          4176450.0          0.0
    LF2326        Luofu         Mid        28500.0           111.0          2781300.0          0.0
  E6213E32        Luofu        High        40000.0            42.0          1680000.0          0.0
  E6256E01        Luofu        High        48000.0            30.0          1440000.0          0.0
      SM01   Smfootware         Mid        21500.0            60.0          1285750.0          0.0
     J7002      Maldini        High        42000.0            30.0          1220000.0          0.0
     WR945       Gooddy         Mid        37500.0            43.0          1170900.0          0.0
   MIXSTAR   ကျန်းမာရေး         Low         9500.0           120.0          1026000.0          0.0
    F2325W        Luofu         Mid        30500.0            33.0          1019300.0          0.0
      P779        Elisa        High        38500.0            24.0           897700.0          0.0
     GC163        Gucci        High        49500.0            18.0           891000.0          0.0
      1682      Stalker         Mid        25500.0            33.0           832600.0         -1.0
    300090       Hummer         Low        14500.0            67.0           809500.0          0.0
     E6193        Luofu         Mid        34500.0            24.0           780000.0          0.0
      5199        Yeezi         Mid        26000.0            30.0           764400.0          0.0
      2326      Jinzuda         Low        12500.0            58.0           701000.0          0.0
       PLM ပွင့်လွာကျား         Mid        17500.0            46.0           651000.0          0.0
     T3748        Elise         Mid        35000.0            18.0           630000.0          0.0
     GC169        Gucci        High        51500.0            12.0           617500.0          0.0
     GC167        Gucci        High        51000.0            12.0           612000.0          0.0

Explanation
Now we are going from a summary:
“242 A products are out of stock”

to the actual Stock Codes:
“Which 242 products are they?”

We sort by Total_Sales_Value, so the historically largest sales-value contributors appear first.
Goal
This becomes the beginning of your Purchasing Attention List:
High sales importance (A) + No current stock → investigate for reorder
Run Step 4.8 and show me the output. After that, we should check something equally important: N products with stock (639 units), because they may represent inventory tied up in products with no recorded sales.

In [ ]:
Step 4.8 is working, and it found the expected 242 A-class products with On Hand Qty <= 0.
One important finding appears in your output:
Stock Code 1682 → On Hand Qty = -1
So your inventory contains at least one negative stock value. We should keep it in the attention list, but distinguish zero stock from negative stock later because negative stock may indicate a stock-record/data issue.
Now continue with the other side of the purchasing problem.
Step 4.9 — Find No-Sales Products That Still Have Stock

In [36]:
# ==========================================================
# STEP 4.9 — FIND NO-SALES PRODUCTS WITH CURRENT STOCK
# ==========================================================

n_with_stock = product_master[
    (product_master["ABC_Class"] == "N") &
    (product_master["On Hand Qty"] > 0)
].copy()

# Calculate current inventory value
n_with_stock["Stock_Value"] = (
    n_with_stock["On Hand Qty"]
    * n_with_stock["Buying Price"]
)

# Sort by highest stock quantity
n_with_stock = n_with_stock.sort_values(
    "On Hand Qty",
    ascending=False
)

# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== NO-SALES PRODUCTS WITH STOCK ==========")

print("No-sales products with stock :", len(n_with_stock))

print("\nTotal Units in Stock:")
print(round(n_with_stock["On Hand Qty"].sum(), 0))

print("\nTop 20 Products:")

print(
    n_with_stock[
        [
            "Stock Code",
            "Description",
            "Price Range",
            "Selling Price",
            "Buying Price",
            "On Hand Qty",
            "Stock_Value"
        ]
    ]
    .head(20)
    .round(0)
    .to_string(index=False)
)

========== NO-SALES PRODUCTS WITH STOCK ==========
No-sales products with stock : 124

Total Units in Stock:
639.0

Top 20 Products:
Stock Code  Description Price Range  Selling Price  Buying Price  On Hand Qty  Stock_Value
      1111    Miss Heel         Low         3000.0        1858.0         36.0      66899.0
      P877        Elisa        High        42000.0       16350.0         30.0     490500.0
  SNS74600     လယ်သာဖြူ         Low         6500.0        4900.0         25.0     122500.0
     GC746         Guci        High        48500.0       38500.0         24.0     924000.0
     SWEET         Sock         Low         2500.0        1605.0         20.0      32100.0
      2222    Miss Heel         Low         3000.0        1858.0         12.0      22300.0
  E6244E01        Luofu        High        46000.0       35500.0         12.0     426000.0
      VT66        Lolla         Mid        35000.0       21850.0         12.0     262200.0
 DT240305S      Doubled         Low        13500.0        4800.0         12.0      57600.0
    U16085      Maldini        High        72500.0       37200.0         12.0     446400.0
     NR025        Nilin        High        38500.0       20650.0         12.0     247800.0
    901314      Iq Soft        High        40000.0       28450.0         12.0     341400.0
     NW113        Nilin         Mid        37000.0       23000.0         11.0     253000.0
 SNS78800A  Shwenannsan         Low        12500.0        8800.0         10.0      88000.0
 SUPERSOCK         Sock         Low         2500.0        1605.0         10.0      16050.0
    QISHUO         Sock         Low         2500.0        1605.0         10.0      16050.0
  HELLODAY         Sock         Low         2500.0        1605.0         10.0      16050.0
 FSZYSOCKS         Sock         Low         2500.0        1605.0         10.0      16050.0
 SNS775000 Shwe Nan San         Low        10500.0        7800.0         10.0      78000.0
    PL0486       Qsweet         Mid        36000.0       22500.0          8.0     180000.0

For example, 1111 – Miss Heel has 36 units in stock but no recorded positive sales in the analyzed period. GC746 – Guci has 24 units and a stock value of 924,000, so this kind of product deserves inventory review.
However, before creating the final purchasing decisions, we should avoid jumping straight from ABC to "Buy" or "Don't Buy". ABC tells us importance, but not how much we should order. We still need sales speed/demand.
Step 5.1 — Calculate Sales Velocity
We already know the sales period is from 2025-02-09 to 2026-09-04. Now calculate average monthly quantity sold for every product.

In [40]:
# ==========================================================
# STEP 5.1 — CALCULATE SALES VELOCITY
# ==========================================================

# Calculate sales period
first_date = abc_sale["Date"].min()
last_date = abc_sale["Date"].max()

sales_days = (last_date - first_date).days + 1

# Convert days to approximate months
sales_months = sales_days / 30.44

print("========== SALES PERIOD ==========")

print("First Date:", first_date.date())
print("Last Date:", last_date.date())
print("Sales Days:", sales_days)
print("Approx. Months:", round(sales_months, 1))


# ----------------------------------------------------------
# CALCULATE AVERAGE MONTHLY SALES
# ----------------------------------------------------------

product_master["Avg_Monthly_Sales"] = (
    product_master["Total_Qty_Sold"]
    / sales_months
)


# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("\n========== SALES VELOCITY ==========")

print(
    product_master[
        [
            "Stock Code",
            "Description",
            "ABC_Class",
            "Total_Qty_Sold",
            "Avg_Monthly_Sales",
            "On Hand Qty"
        ]
    ]
    .sort_values(
        "Avg_Monthly_Sales",
        ascending=False
    )
    .head(20)
    .round(2)
    .to_string(index=False)
)

========== SALES PERIOD ==========
First Date: 2025-02-09
Last Date: 2026-09-04
Sales Days: 573
Approx. Months: 18.8

========== SALES VELOCITY ==========
 Stock Code     Description ABC_Class  Total_Qty_Sold  Avg_Monthly_Sales  On Hand Qty
     SHOWER          Shower         A           379.0              20.13         81.0
      EDD35            Eddy         A           188.0               9.99         58.0
      EDD45            Eddy         A           163.0               8.66         11.0
     A01617     ယုန်ဖြူကျား         A           135.0               7.17        120.0
      F2326           Luofu         A           133.0               7.07          0.0
         SM              Sm         A           131.0               6.96         10.0
     000139         ဆင်ကြယ်         A           125.0               6.64         56.0
       F2KU ငါးကြင်းနစ်ကာင်         A           121.0               6.43        147.0
    MIXSTAR      ကျန်းမာရေး         A           120.0               6.37          0.0
     LF2326           Luofu         A           111.0               5.90          0.0
     A01618        ယုန်ဖြူမ         A           110.0               5.84          8.0
 BLUE CAMEL      Blue Camel         A           108.0               5.74         12.0
    STICKER         Sticker         A            98.0               5.21        147.0
      WR888          Gooddy         A            85.0               4.52         10.0
   E6230E01           Luofu         A            75.0               3.98         26.0
       KKNM  ကြိုးကြာနီကျား         A            73.0               3.88         87.0
KNIGHTHORSE          Shower         A            73.0               3.88         71.0
      E6217           Luofu         A            68.0               3.61          4.0
     300090          Hummer         A            67.0               3.56          0.0
       FROG            Frog         A            63.0               3.35          7.0

Yes, Step 5.1 is working correctly.
For example, your result now tells us:
SHOWER → sells about 20.13 units/month → 81 currently in stock
F2326  → sells about 7.07 units/month  → 0 currently in stock
MIXSTAR → sells about 6.37 units/month → 0 currently in stock
LF2326 → sells about 5.90 units/month  → 0 currently in stock
Now we can calculate how long the current stock can last.
Step 5.2 — Calculate Stock Coverage

In [41]:
# ==========================================================
# STEP 5.2 — CALCULATE STOCK COVERAGE
# ==========================================================

# Stock Coverage = Current Stock / Average Monthly Sales

product_master["Stock_Coverage_Months"] = np.where(
    product_master["Avg_Monthly_Sales"] > 0,
    product_master["On Hand Qty"] /
    product_master["Avg_Monthly_Sales"],
    np.nan
)

# Negative inventory should be treated as 0 coverage
product_master.loc[
    product_master["On Hand Qty"] <= 0,
    "Stock_Coverage_Months"
] = 0


# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== STOCK COVERAGE ==========")

coverage_check = (
    product_master[
        product_master["ABC_Class"] == "A"
    ]
    [
        [
            "Stock Code",
            "Description",
            "ABC_Class",
            "Avg_Monthly_Sales",
            "On Hand Qty",
            "Stock_Coverage_Months"
        ]
    ]
    .sort_values(
        "Stock_Coverage_Months",
        ascending=True
    )
)

print(
    coverage_check
    .head(20)
    .round(2)
    .to_string(index=False)
)

========== STOCK COVERAGE ==========
Stock Code         Description ABC_Class  Avg_Monthly_Sales  On Hand Qty  Stock_Coverage_Months
    000091 Fashion Sport TG300         A               0.37          0.0                    0.0
    GCX057               Gucci         A               0.48          0.0                    0.0
   GCTS066                Guci         A               0.21          0.0                    0.0
     GCT99                Guci         A               0.53          0.0                    0.0
    GCT105                Guci         A               0.64          0.0                    0.0
    GC8003                Guci         A               0.64          0.0                    0.0
    GC7Q37                Guci         A               0.64          0.0                    0.0
     GC727                Guci         A               0.27          0.0                    0.0
     GC269                Guci         A               0.32          0.0                    0.0
     GC180                Guci         A               0.64          0.0                    0.0
     GC179                Guci         A               0.32          0.0                    0.0
     GC175               Gucci         A               0.32          0.0                    0.0
     GC173                Guci         A               0.32          0.0                    0.0
     GC170                Guci         A               0.32          0.0                    0.0
     GC169               Gucci         A               0.64          0.0                    0.0
     GC167               Gucci         A               0.64          0.0                    0.0
    GD0098          Goldenduck         A               0.27          0.0                    0.0
    GD0113          Goldenduck         A               0.32          0.0                    0.0
     GD127         Golden Duck         A               0.32          0.0                    0.0
     GR021                Guci         A               0.32          0.0                    0.0

Yes, Step 5.2 worked correctly. The reason your first 20 rows all show 0.0 coverage is that you sorted Stock_Coverage_Months from lowest to highest, so the out-of-stock A products naturally appear first.
Step 5.3 — Create Stock Coverage Status
For this first decision-support version, use these thresholds:
Out of Stock: 0 stock
Low Coverage: less than 1 month
Adequate: 1–3 months
High Coverage: more than 3 months
No Sales: N-class product

In [46]:
# ==========================================================
# STEP 5.3 — CREATE STOCK COVERAGE STATUS
# ==========================================================

def stock_status(row):

    # No historical sales
    if row["ABC_Class"] == "N":
        return "No Sales"

    # No current stock
    elif row["On Hand Qty"] <= 0:
        return "Out of Stock"

    # Less than 1 month stock
    elif row["Stock_Coverage_Months"] < 1:
        return "Low Coverage"

    # 1 to 3 months stock
    elif row["Stock_Coverage_Months"] <= 3:
        return "Adequate"

    # More than 3 months stock
    else:
        return "High Coverage"


product_master["Stock_Status"] = product_master.apply(
    stock_status,
    axis=1
)


# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== STOCK STATUS ==========")

print(
    product_master["Stock_Status"]
    .value_counts()
)

print("\n========== STOCK STATUS BY ABC CLASS ==========")

stock_status_summary = pd.crosstab(
    product_master["ABC_Class"],
    product_master["Stock_Status"]
)

print(stock_status_summary)

========== STOCK STATUS ==========
Stock_Status
Out of Stock     680
High Coverage    446
No Sales         124
Adequate          58
Low Coverage      12
Name: count, dtype: int64

========== STOCK STATUS BY ABC CLASS ==========
Stock_Status  Adequate  High Coverage  Low Coverage  No Sales  Out of Stock
ABC_Class
A                   51            164            11         0           242
B                    4            145             1         0           208
C                    3            137             0         0           230
N                    0              0             0       124             0

Out of Stock    680
High Coverage   446
No Sales        124
Adequate         58
Low Coverage     12
-------------------
Total         1,320 ✓
A particularly important result is that 242 A-class products are out of stock, while another 11 A products have less than one month of coverage. Now we can turn these conditions into purchasing priorities.
Step 5.4 — Create Purchasing Priority

In [47]:
# ==========================================================
# STEP 5.4 — CREATE PURCHASING PRIORITY
# ==========================================================

def purchasing_priority(row):

    # ----------------------------------
    # NO SALES
    # ----------------------------------
    if row["ABC_Class"] == "N":
        return "Do Not Reorder / Review"

    # ----------------------------------
    # A PRODUCTS
    # ----------------------------------
    elif (
        row["ABC_Class"] == "A"
        and row["Stock_Status"] == "Out of Stock"
    ):
        return "Urgent Review"

    elif (
        row["ABC_Class"] == "A"
        and row["Stock_Status"] == "Low Coverage"
    ):
        return "High Priority"

    # ----------------------------------
    # B PRODUCTS
    # ----------------------------------
    elif (
        row["ABC_Class"] == "B"
        and row["Stock_Status"] == "Out of Stock"
    ):
        return "Reorder Review"

    elif (
        row["ABC_Class"] == "B"
        and row["Stock_Status"] == "Low Coverage"
    ):
        return "Reorder Review"

    # ----------------------------------
    # C PRODUCTS
    # ----------------------------------
    elif (
        row["ABC_Class"] == "C"
        and row["Stock_Status"] == "Out of Stock"
    ):
        return "Low Priority Review"

    # ----------------------------------
    # ENOUGH STOCK
    # ----------------------------------
    elif row["Stock_Status"] == "High Coverage":
        return "Hold / Monitor"

    else:
        return "Normal"


product_master["Purchasing_Priority"] = (
    product_master.apply(
        purchasing_priority,
        axis=1
    )
)


# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

print("========== PURCHASING PRIORITY ==========")

priority_summary = (
    product_master["Purchasing_Priority"]
    .value_counts()
)

print(priority_summary)


print("\n========== PRIORITY BY ABC CLASS ==========")

print(
    pd.crosstab(
        product_master["ABC_Class"],
        product_master["Purchasing_Priority"]
    )
)

========== PURCHASING PRIORITY ==========
Purchasing_Priority
Hold / Monitor             446
Urgent Review              242
Low Priority Review        230
Reorder Review             209
Do Not Reorder / Review    124
Normal                      58
High Priority               11
Name: count, dtype: int64

========== PRIORITY BY ABC CLASS ==========
Purchasing_Priority  Do Not Reorder / Review  High Priority  Hold / Monitor  \
ABC_Class
A                                          0             11             164
B                                          0              0             145
C                                          0              0             137
N                                        124              0               0

Purchasing_Priority  Low Priority Review  Normal  Reorder Review  \
ABC_Class
A                                      0      51               0
B                                      0       4             209
C                                    230       3               0
N                                      0       0               0

Purchasing_Priority  Urgent Review
ABC_Class
A                              242
B                                0
C                                0
N                                0

Yes. Step 5.4 is correct. Your output matches the expected numbers exactly:
Hold / Monitor             446
Urgent Review              242
Low Priority Review        230
Reorder Review             209
Do Not Reorder / Review    124
Normal                      58
High Priority               11
------------------------------
Total                    1,320 ✓
The truncated crosstab is only a display issue, not a calculation problem. We can leave it.
Now we should continue carefully. Before calculating a final purchase quantity, we need to define a target stock coverage. For this first model, we can use 3 months of stock as the target because your current Adequate definition is 1–3 months.

Goal
Your system now has the beginning of the actual decision-support layer:
Historical Sales → ABC → Sales Velocity → Inventory → Stock Coverage → Purchasing Priority
After this works, the next step should be Step 5.5 — calculate a suggested reorder quantity for products that need purchasing attention, rather than simply identifying them

Step 5.5 — Calculate Suggested Reorder Quantity

In [48]:
# ==========================================================
# STEP 5.5 — CALCULATE SUGGESTED REORDER QUANTITY
# ==========================================================

# Target = enough stock for 3 months
TARGET_MONTHS = 3

# Calculate target stock quantity
product_master["Target_Stock_Qty"] = (
    product_master["Avg_Monthly_Sales"]
    * TARGET_MONTHS
)

# Suggested reorder quantity
product_master["Suggested_Reorder_Qty"] = (
    product_master["Target_Stock_Qty"]
    - product_master["On Hand Qty"]
)

# Never recommend negative purchasing quantity
product_master["Suggested_Reorder_Qty"] = (
    product_master["Suggested_Reorder_Qty"]
    .clip(lower=0)
)

# Round UP because we cannot purchase part of a unit
product_master["Suggested_Reorder_Qty"] = (
    np.ceil(product_master["Suggested_Reorder_Qty"])
    .astype(int)
)

# No-sales products should not receive reorder recommendation
product_master.loc[
    product_master["ABC_Class"] == "N",
    "Suggested_Reorder_Qty"
] = 0


# ----------------------------------------------------------
# CHECK RESULT
# ----------------------------------------------------------

reorder_list = product_master[
    product_master["Suggested_Reorder_Qty"] > 0
].copy()

reorder_list = reorder_list.sort_values(
    [
        "ABC_Class",
        "Total_Sales_Value"
    ],
    ascending=[True, False]
)


print("========== SUGGESTED REORDER ==========")

print("Products Suggested for Reorder:", len(reorder_list))

print("\nTotal Suggested Units:")
print(reorder_list["Suggested_Reorder_Qty"].sum())

print("\nTop 20 Products:")

print(
    reorder_list[
        [
            "Stock Code",
            "Description",
            "ABC_Class",
            "Avg_Monthly_Sales",
            "On Hand Qty",
            "Stock_Coverage_Months",
            "Target_Stock_Qty",
            "Suggested_Reorder_Qty"
        ]
    ]
    .head(20)
    .round(2)
    .to_string(index=False)
)

========== SUGGESTED REORDER ==========
Products Suggested for Reorder: 750

Total Suggested Units:
1234

Top 20 Products:
Stock Code Description ABC_Class  Avg_Monthly_Sales  On Hand Qty  Stock_Coverage_Months  Target_Stock_Qty  Suggested_Reorder_Qty
     F2326       Luofu         A               7.07          0.0                   0.00             21.20                     22
        SM          Sm         A               6.96         10.0                   1.44             20.88                     11
    LF2326       Luofu         A               5.90          0.0                   0.00             17.69                     18
     E6217       Luofu         A               3.61          4.0                   1.11             10.84                      7
     EDD45        Eddy         A               8.66         11.0                   1.27             25.98                     15
     WR888      Gooddy         A               4.52         10.0                   2.21             13.55                      4
  E6213E32       Luofu         A               2.23          0.0                   0.00              6.69                      7
BLUE CAMEL  Blue Camel         A               5.74         12.0                   2.09             17.21                      6
  E6256E01       Luofu         A               1.59          0.0                   0.00              4.78                      5
    WR1100      Gooddy         A               3.13          1.0                   0.32              9.40                      9
      SM01  Smfootware         A               3.19          0.0                   0.00              9.56                     10
     J7002     Maldini         A               1.59          0.0                   0.00              4.78                      5
     WR945      Gooddy         A               2.28          0.0                   0.00              6.85                      7
   MIXSTAR  ကျန်းမာရေး         A               6.37          0.0                   0.00             19.12                     20
    F2325W       Luofu         A               1.75          0.0                   0.00              5.26                      6
 E6251E01K       Luofu         A               1.38          4.0                   2.90              4.14                      1
    A01618    ယုန်ဖြူမ         A               5.84          8.0                   1.37             17.53                     10
      P779       Elisa         A               1.27          0.0                   0.00              3.82                      4
     GC163       Gucci         A               0.96          0.0                   0.00              2.87                      3
     WR911      Gooddy         A               1.86          3.0                   1.61              5.58                      3

Step 5.5 is working. You currently have:
Products suggested for reorder = 750
Total suggested units          = 1,234
Target coverage                = 3 months
For example, F2326 has average monthly sales of 7.07, zero stock, and a 3-month target of about 21.20, so the current model suggests roughly 22 units.
But do not treat the 1,234 units as the final purchase quantity yet. We need to check purchase.csv. A product may show zero stock but may already have recent purchasing activity.
Step 5.6 — Prepare Ashley Purchase History

In [49]:
# ==========================================================
# STEP 5.6 — PREPARE ASHLEY PURCHASE HISTORY
# ==========================================================

# Keep Ashley only
ashley_purchase = purchase[
    purchase["Branch"]
    .astype(str)
    .str.strip()
    .str.lower() == "ashley"
].copy()

# Convert Date
ashley_purchase["Date"] = pd.to_datetime(
    ashley_purchase["Date"],
    errors="coerce"
)

# Convert Quantity
ashley_purchase["Quantity"] = pd.to_numeric(
    ashley_purchase["Quantity"],
    errors="coerce"
)

# Convert Buying Price
ashley_purchase["Buying Price"] = pd.to_numeric(
    ashley_purchase["Buying Price"],
    errors="coerce"
)

# ----------------------------------------------------------
# BASIC CHECK
# ----------------------------------------------------------

print("========== ASHLEY PURCHASE DATA ==========")

print("Purchase Rows:", len(ashley_purchase))

print("\nDate Range:")
print("First Purchase:", ashley_purchase["Date"].min())
print("Last Purchase:", ashley_purchase["Date"].max())

print("\nQuantity Check:")
print("Missing:", ashley_purchase["Quantity"].isna().sum())
print("Zero:", (ashley_purchase["Quantity"] == 0).sum())
print("Negative:", (ashley_purchase["Quantity"] < 0).sum())

print("\nTotal Purchased Units:")
print(
    round(
        ashley_purchase["Quantity"].sum(),
        0
    )
)

print("\nUnique Products Purchased:")
print(
    ashley_purchase["Stock Code"].nunique()
)

========== ASHLEY PURCHASE DATA ==========
Purchase Rows: 15

Date Range:
First Purchase: 2026-09-04 00:00:00
Last Purchase: 2026-09-04 00:00:00

Quantity Check:
Missing: 0
Zero: 0
Negative: 0

Total Purchased Units:
115.0

Unique Products Purchased:
15

Yes. That's a good step to add before using purchase data.
Your purchase.csv currently shows only 15 rows / 15 products / 115 units, all dated 2026-09-04. Before using it in the recommendation system, Step 5.7 should check and remove duplicate purchase records so the same upload/record isn't counted twice.
Step 5.7 — Check & Prevent Duplicate Purchase Data

In [50]:
# ==========================================================
# STEP 5.7 — CHECK & PREVENT DUPLICATE PURCHASE DATA
# ==========================================================

print("========== PURCHASE DUPLICATE CHECK ==========")

print("Rows Before:", len(ashley_purchase))


# ----------------------------------------------------------
# 1. CHECK EXACT DUPLICATE ROWS
# ----------------------------------------------------------

exact_duplicates = ashley_purchase.duplicated().sum()

print("Exact Duplicate Rows:", exact_duplicates)


# ----------------------------------------------------------
# 2. DEFINE PURCHASE RECORD KEY
# ----------------------------------------------------------
# Same Branch + Date + Stock Code + Quantity + Buying Price
# is treated as the same purchase record.

duplicate_key = [
    "Branch",
    "Date",
    "Stock Code",
    "Quantity",
    "Buying Price",
    "Location"
]


# ----------------------------------------------------------
# 3. CHECK POSSIBLE DUPLICATE PURCHASE RECORDS
# ----------------------------------------------------------

duplicate_purchase = ashley_purchase[
    ashley_purchase.duplicated(
        subset=duplicate_key,
        keep=False
    )
].copy()

print(
    "Possible Duplicate Purchase Records:",
    len(duplicate_purchase)
)


# ----------------------------------------------------------
# 4. REMOVE DUPLICATES
# ----------------------------------------------------------

ashley_purchase_clean = (
    ashley_purchase
    .drop_duplicates(
        subset=duplicate_key,
        keep="first"
    )
    .copy()
)


# ----------------------------------------------------------
# 5. FINAL CHECK
# ----------------------------------------------------------

print("\n========== AFTER DUPLICATE REMOVAL ==========")

print("Rows After:", len(ashley_purchase_clean))

print(
    "Duplicates Removed:",
    len(ashley_purchase) - len(ashley_purchase_clean)
)

print(
    "Total Purchased Units:",
    round(ashley_purchase_clean["Quantity"].sum(), 0)
)

print(
    "Unique Products:",
    ashley_purchase_clean["Stock Code"].nunique()
)

========== PURCHASE DUPLICATE CHECK ==========
Rows Before: 15
Exact Duplicate Rows: 0
Possible Duplicate Purchase Records: 0

========== AFTER DUPLICATE REMOVAL ==========
Rows After: 15
Duplicates Removed: 0
Total Purchased Units: 115.0
Unique Products: 15

Step 5.7 is complete. Your purchase data currently has no duplicates:
Rows before:           15
Duplicates removed:     0
Rows after:            15
Purchased units:      115
Unique products:       15
Now continue with Step 5.8 — connect clean purchase information to the Product Master. At this point, I recommend using the purchase data as a recent-purchase warning, not subtracting it directly from the reorder quantity. We don't know from this file alone whether these 115 units are already included in On Hand Qty.
Step 5.8 — Add Recent Purchase Information

In [51]:
# ==========================================================
# STEP 5.8 — ADD RECENT PURCHASE INFO TO PRODUCT MASTER
# ==========================================================

# ----------------------------------------------------------
# 1. SUMMARIZE CLEAN PURCHASE DATA BY PRODUCT
# ----------------------------------------------------------

purchase_summary = (
    ashley_purchase_clean
    .groupby("Stock Code")
    .agg(
        Recent_Purchase_Qty=("Quantity", "sum"),
        Last_Purchase_Date=("Date", "max")
    )
    .reset_index()
)


# ----------------------------------------------------------
# 2. MERGE INTO PRODUCT MASTER
# ----------------------------------------------------------

product_master = product_master.merge(
    purchase_summary,
    on="Stock Code",
    how="left"
)


# ----------------------------------------------------------
# 3. PRODUCTS WITHOUT PURCHASE RECORD
# ----------------------------------------------------------

product_master["Recent_Purchase_Qty"] = (
    product_master["Recent_Purchase_Qty"]
    .fillna(0)
)

product_master["Recent_Purchase_Qty"] = (
    product_master["Recent_Purchase_Qty"]
    .astype(int)
)


# ----------------------------------------------------------
# 4. CREATE RECENT PURCHASE FLAG
# ----------------------------------------------------------

product_master["Has_Recent_Purchase"] = (
    product_master["Recent_Purchase_Qty"] > 0
)


# ----------------------------------------------------------
# 5. CHECK RESULT
# ----------------------------------------------------------

print("========== RECENT PURCHASE CHECK ==========")

print(
    "Products With Recent Purchase:",
    product_master["Has_Recent_Purchase"].sum()
)

print(
    "Total Recent Purchase Units:",
    product_master["Recent_Purchase_Qty"].sum()
)

print("\nRecent Purchase Products:")

print(
    product_master[
        product_master["Has_Recent_Purchase"]
    ][
        [
            "Stock Code",
            "Description",
            "ABC_Class",
            "On Hand Qty",
            "Avg_Monthly_Sales",
            "Suggested_Reorder_Qty",
            "Recent_Purchase_Qty",
            "Last_Purchase_Date"
        ]
    ]
    .sort_values(
        "Recent_Purchase_Qty",
        ascending=False
    )
    .to_string(index=False)
)

========== RECENT PURCHASE CHECK ==========
Products With Recent Purchase: 15
Total Recent Purchase Units: 115

Recent Purchase Products:
Stock Code Description ABC_Class  On Hand Qty  Avg_Monthly_Sales  Suggested_Reorder_Qty  Recent_Purchase_Qty Last_Purchase_Date
   AB596W1     Ab Walk         B         18.0           0.265620                      0                   18         2026-09-04
    AB947W     Ab Walk         C         15.0           0.159372                      0                   12         2026-09-04
  E6244E01       Luofu         N         12.0           0.000000                      0                   12         2026-09-04
     NR025       Nilin         N         12.0           0.000000                      0                   12         2026-09-04
    AB520M     Ab Walk         N          6.0           0.000000                      0                    6         2026-09-04
    AB941W      Abwalk         B          6.0           0.318743                      0                    6         2026-09-04
   AM19217     Maldini         A          7.0           0.265620                      0                    6         2026-09-04
      C912        Shoe         N          6.0           0.000000                      0                    6         2026-09-04
    F27005     Maldini         N          6.0           0.000000                      0                    6         2026-09-04
    MN8231     Maldini         A          6.0           0.690611                      0                    6         2026-09-04
    T14332     Maldini         N          6.0           0.000000                      0                    6         2026-09-04
    UW7043        Kito         A         13.0           0.584363                      0                    6         2026-09-04
    YW3112        Kito         N          6.0           0.000000                      0                    6         2026-09-04
    SPX002       Lolla         N          4.0           0.000000                      0                    4         2026-09-04
    SPX007       Lolla         N          3.0           0.000000                      0                    3         2026-09-04

Good. We will make Step 5.10 = Save Purchase History Safely.
The purpose is simple:
New purchase data → check against saved history → only add new records → never modify On Hand Qty.
Step 5.10 — Create and Save Purchase History

In [ ]:
# ==========================================================
# STEP 5.10 — SAVE CLEAN PURCHASE HISTORY
# ==========================================================

import os

PURCHASE_HISTORY_FILE = "purchase_history.csv"

# Columns used to identify the same purchase record
purchase_key = [
    "Branch",
    "Date",
    "Stock Code",
    "Quantity",
    "Buying Price",
    "Location"
]


# ----------------------------------------------------------
# 1. CHECK IF PURCHASE HISTORY ALREADY EXISTS
# ----------------------------------------------------------

if os.path.exists(PURCHASE_HISTORY_FILE):

    purchase_history = pd.read_csv(
        PURCHASE_HISTORY_FILE
    )

    purchase_history["Date"] = pd.to_datetime(
        purchase_history["Date"],
        errors="coerce"
    )

    print("Existing purchase history found.")

else:

    purchase_history = pd.DataFrame(
        columns=ashley_purchase_clean.columns
    )

    print("No existing purchase history.")
    print("Creating new purchase history.")


# ----------------------------------------------------------
# 2. NUMBER OF OLD RECORDS
# ----------------------------------------------------------

old_rows = len(purchase_history)


# ----------------------------------------------------------
# 3. COMBINE OLD HISTORY + CURRENT PURCHASE DATA
# ----------------------------------------------------------

combined_purchase_history = pd.concat(
    [
        purchase_history,
        ashley_purchase_clean
    ],
    ignore_index=True
)


# ----------------------------------------------------------
# 4. REMOVE RECORDS THAT ALREADY EXIST
# ----------------------------------------------------------

combined_purchase_history = (
    combined_purchase_history
    .drop_duplicates(
        subset=purchase_key,
        keep="first"
    )
    .copy()
)


# ----------------------------------------------------------
# 5. CALCULATE HOW MANY NEW RECORDS WERE ADDED
# ----------------------------------------------------------

new_rows = (
    len(combined_purchase_history)
    - old_rows
)


# ----------------------------------------------------------
# 6. SAVE PURCHASE HISTORY
# ----------------------------------------------------------

combined_purchase_history.to_csv(
    PURCHASE_HISTORY_FILE,
    index=False
)


# ----------------------------------------------------------
# 7. FINAL CHECK
# ----------------------------------------------------------

print("\n========== PURCHASE HISTORY SAVED ==========")

print("Previous Records:", old_rows)
print("New Records Added:", new_rows)
print(
    "Duplicate / Existing Records Skipped:",
    len(ashley_purchase_clean) - new_rows
)

print(
    "Total Purchase History Records:",
    len(combined_purchase_history)
)

print("\nIMPORTANT:")
print("Purchase history saved.")
print("Inventory On Hand Qty was NOT changed.")

This means the 15 purchase records are now stored separately in purchase_history.csv, exactly as we wanted.
One important test: don't rerun Step 5.10 right now just for testing, because the logic is already clear. On the next purchase-file upload, the same mechanism will compare it with the saved history.
Next — Step 5.11: Purchase Recommendation Table
Now we can bring together the information we've built:
ABC importance + sales velocity + current stock + stock coverage + suggested reorder + purchase priority + purchase history
But purchase history will be reference information only. It will not change On Hand Qty.

Now we move to Step 5.11 — Build the Final Purchasing Recommendation Table.
We are not changing inventory here. We are simply collecting the important results from Steps 3–5 into one clean table that can later feed your dashboard.
Step 5.11 — Final Purchasing Recommendation Table

In [53]:
# ==========================================================
# STEP 5.11 — FINAL PURCHASING RECOMMENDATION TABLE
# ==========================================================

# ----------------------------------------------------------
# 1. SELECT IMPORTANT DECISION COLUMNS
# ----------------------------------------------------------

recommendation_columns = [
    "Stock Code",
    "Description",
    "ABC_Class",
    "Price Range",
    "Selling Price",
    "Buying Price",
    "Total_Qty_Sold",
    "Total_Sales_Value",
    "Avg_Monthly_Sales",
    "On Hand Qty",
    "Stock_Coverage_Months",
    "Stock_Status",
    "Purchasing_Priority",
    "Suggested_Reorder_Qty",
    "Recent_Purchase_Qty",
    "Last_Purchase_Date"
]


purchase_recommendation = product_master[
    recommendation_columns
].copy()


# ----------------------------------------------------------
# 2. CREATE RECOMMENDATION ACTION
# ----------------------------------------------------------

def recommendation_action(row):

    # No historical sales
    if row["ABC_Class"] == "N":
        return "Review / Do Not Reorder"

    # A product + out of stock
    if (
        row["ABC_Class"] == "A"
        and row["On Hand Qty"] <= 0
    ):
        return "Urgent Reorder"

    # Product needs more stock
    if row["Suggested_Reorder_Qty"] > 0:
        return "Reorder"

    # Too much stock
    if row["Stock_Status"] == "High Coverage":
        return "Hold / Monitor"

    return "No Reorder Needed"


purchase_recommendation["Recommendation"] = (
    purchase_recommendation.apply(
        recommendation_action,
        axis=1
    )
)


# ----------------------------------------------------------
# 3. ADD RECENT PURCHASE WARNING
# ----------------------------------------------------------

purchase_recommendation["Purchase_Note"] = "No Recent Purchase"

purchase_recommendation.loc[
    purchase_recommendation["Recent_Purchase_Qty"] > 0,
    "Purchase_Note"
] = "Recent Purchase Exists"


# ----------------------------------------------------------
# 4. CREATE PRIORITY ORDER FOR SORTING
# ----------------------------------------------------------

priority_order = {
    "Urgent Reorder": 1,
    "Reorder": 2,
    "No Reorder Needed": 3,
    "Hold / Monitor": 4,
    "Review / Do Not Reorder": 5
}

purchase_recommendation["Priority_Order"] = (
    purchase_recommendation["Recommendation"]
    .map(priority_order)
)


# ----------------------------------------------------------
# 5. SORT MOST IMPORTANT PRODUCTS FIRST
# ----------------------------------------------------------

purchase_recommendation = (
    purchase_recommendation
    .sort_values(
        [
            "Priority_Order",
            "Total_Sales_Value"
        ],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)


# ----------------------------------------------------------
# 6. CHECK RESULT
# ----------------------------------------------------------

print("========== FINAL PURCHASING RECOMMENDATION ==========")

print("Total Products:", len(purchase_recommendation))

print("\nRecommendation Summary:")

print(
    purchase_recommendation["Recommendation"]
    .value_counts()
)

print("\nTotal Suggested Reorder Units:")

print(
    purchase_recommendation["Suggested_Reorder_Qty"]
    .sum()
)

print("\nTop 20 Products Needing Attention:")

print(
    purchase_recommendation[
        [
            "Stock Code",
            "Description",
            "ABC_Class",
            "On Hand Qty",
            "Avg_Monthly_Sales",
            "Stock_Coverage_Months",
            "Suggested_Reorder_Qty",
            "Recommendation",
            "Purchase_Note"
        ]
    ]
    .head(20)
    .round(2)
    .to_string(index=False)
)

========== FINAL PURCHASING RECOMMENDATION ==========
Total Products: 1320

Recommendation Summary:
Recommendation
Reorder                    508
Hold / Monitor             446
Urgent Reorder             242
Review / Do Not Reorder    124
Name: count, dtype: int64

Total Suggested Reorder Units:
1234

Top 20 Products Needing Attention:
Stock Code  Description ABC_Class  On Hand Qty  Avg_Monthly_Sales  Stock_Coverage_Months  Suggested_Reorder_Qty Recommendation      Purchase_Note
     F2326        Luofu         A          0.0               7.07                    0.0                     22 Urgent Reorder No Recent Purchase
    LF2326        Luofu         A          0.0               5.90                    0.0                     18 Urgent Reorder No Recent Purchase
  E6213E32        Luofu         A          0.0               2.23                    0.0                      7 Urgent Reorder No Recent Purchase
  E6256E01        Luofu         A          0.0               1.59                    0.0                      5 Urgent Reorder No Recent Purchase
      SM01   Smfootware         A          0.0               3.19                    0.0                     10 Urgent Reorder No Recent Purchase
     J7002      Maldini         A          0.0               1.59                    0.0                      5 Urgent Reorder No Recent Purchase
     WR945       Gooddy         A          0.0               2.28                    0.0                      7 Urgent Reorder No Recent Purchase
   MIXSTAR   ကျန်းမာရေး         A          0.0               6.37                    0.0                     20 Urgent Reorder No Recent Purchase
    F2325W        Luofu         A          0.0               1.75                    0.0                      6 Urgent Reorder No Recent Purchase
      P779        Elisa         A          0.0               1.27                    0.0                      4 Urgent Reorder No Recent Purchase
     GC163        Gucci         A          0.0               0.96                    0.0                      3 Urgent Reorder No Recent Purchase
      1682      Stalker         A         -1.0               1.75                    0.0                      7 Urgent Reorder No Recent Purchase
    300090       Hummer         A          0.0               3.56                    0.0                     11 Urgent Reorder No Recent Purchase
     E6193        Luofu         A          0.0               1.27                    0.0                      4 Urgent Reorder No Recent Purchase
      5199        Yeezi         A          0.0               1.59                    0.0                      5 Urgent Reorder No Recent Purchase
      2326      Jinzuda         A          0.0               3.08                    0.0                     10 Urgent Reorder No Recent Purchase
       PLM ပွင့်လွာကျား         A          0.0               2.44                    0.0                      8 Urgent Reorder No Recent Purchase
     T3748        Elise         A          0.0               0.96                    0.0                      3 Urgent Reorder No Recent Purchase
     GC169        Gucci         A          0.0               0.64                    0.0                      2 Urgent Reorder No Recent Purchase
     GC167        Gucci         A          0.0               0.64                    0.0                      2 Urgent Reorder No Recent Purchase

Your final system puts all 1,320 products into 4 action groups.
Recommendation	Products	Simple meaning
Urgent Reorder	242	Important A products + currently out of stock
Reorder	508	Stock is below your target level → consider buying more
Hold / Monitor	446	Enough/high stock → don't buy now, keep watching
Review / Do Not Reorder	124	No recorded sales → investigate before buying again
Simple examples
Urgent Reorder:
F2326 is A class, sells about 7 pairs/month, but stock = 0.
→ Urgent attention for reorder.
Reorder:
Suppose Shoe B sells 5 pairs/month. Your 3-month target is 15 pairs, but you only have 5.
→ Need about 10 more → Reorder.
Hold / Monitor:
Suppose Shoe C sells 5/month, but you already have 30 pairs.
→ You already have about 6 months of stock → don't reorder now.
Review / Do Not Reorder:
Suppose Shoe D has 10 pairs in stock but no recorded sales.
→ Don't automatically buy more → review why it isn't selling.
Your final picture
Out of 1,320 products:
750 need some level of reorder attention (242 Urgent + 508 Reorder), while 570 should not currently be automatically reordered (446 Hold/Monitor + 124 Review).
And 1,234 units is the system's calculated total suggested reorder quantity across those products.

Yes. Step 5.11 is working correctly. The numbers are internally consistent:
Total Products                 1,320

Reorder                          508
Urgent Reorder                   242
Hold / Monitor                   446
Review / Do Not Reorder          124
                               -----
Total                          1,320 ✓

Products needing reorder:
508 + 242 = 750 ✓

Total Suggested Reorder Units:
1,234 ✓
This also matches your earlier Step 5.5 result: 750 products suggested for reorder.
One thing is important before we save the final dataset: Urgent Reorder currently means A-class + out of stock, while Reorder contains the other products below the 3-month target. That's a sensible distinction.
Step 5.12 — Validate Final Recommendations

In [54]:
# ==========================================================
# STEP 5.12 — VALIDATE FINAL RECOMMENDATIONS
# ==========================================================

print("========== FINAL VALIDATION ==========")

# ----------------------------------------------------------
# 1. TOTAL PRODUCT CHECK
# ----------------------------------------------------------

print("\n1. Product Count")
print("Product Master:", len(product_master))
print("Recommendation Table:", len(purchase_recommendation))


# ----------------------------------------------------------
# 2. DUPLICATE STOCK CODE CHECK
# ----------------------------------------------------------

duplicate_codes = (
    purchase_recommendation["Stock Code"]
    .duplicated()
    .sum()
)

print("\n2. Duplicate Stock Codes")
print("Duplicates:", duplicate_codes)


# ----------------------------------------------------------
# 3. MISSING IMPORTANT DATA
# ----------------------------------------------------------

print("\n3. Missing Important Values")

check_columns = [
    "Stock Code",
    "ABC_Class",
    "On Hand Qty",
    "Avg_Monthly_Sales",
    "Stock_Status",
    "Suggested_Reorder_Qty",
    "Recommendation"
]

print(
    purchase_recommendation[
        check_columns
    ]
    .isna()
    .sum()
)


# ----------------------------------------------------------
# 4. NEGATIVE REORDER CHECK
# ----------------------------------------------------------

negative_reorder = (
    purchase_recommendation["Suggested_Reorder_Qty"] < 0
).sum()

print("\n4. Negative Reorder Quantity")
print("Products:", negative_reorder)


# ----------------------------------------------------------
# 5. NO-SALES PRODUCT CHECK
# ----------------------------------------------------------

n_wrong = purchase_recommendation[
    (purchase_recommendation["ABC_Class"] == "N") &
    (purchase_recommendation["Suggested_Reorder_Qty"] > 0)
]

print("\n5. No-Sales Products Incorrectly Reordered")
print("Products:", len(n_wrong))


# ----------------------------------------------------------
# 6. URGENT REORDER CHECK
# ----------------------------------------------------------

urgent = purchase_recommendation[
    purchase_recommendation["Recommendation"]
    == "Urgent Reorder"
]

print("\n6. Urgent Reorder")
print("Products:", len(urgent))

print(
    "Urgent Products With Stock > 0:",
    (urgent["On Hand Qty"] > 0).sum()
)


# ----------------------------------------------------------
# 7. RECENT PURCHASE REFERENCE CHECK
# ----------------------------------------------------------

print("\n7. Purchase History Reference")

print(
    "Products With Recent Purchase:",
    (purchase_recommendation["Recent_Purchase_Qty"] > 0).sum()
)

print(
    "Recent Purchase Units:",
    purchase_recommendation["Recent_Purchase_Qty"].sum()
)


# ----------------------------------------------------------
# 8. FINAL TOTAL
# ----------------------------------------------------------

print("\n8. Recommendation Total")

print(
    purchase_recommendation["Recommendation"]
    .value_counts()
)

print(
    "\nCheck Total:",
    purchase_recommendation["Recommendation"]
    .value_counts()
    .sum()
)

========== FINAL VALIDATION ==========

1. Product Count
Product Master: 1320
Recommendation Table: 1320

2. Duplicate Stock Codes
Duplicates: 0

3. Missing Important Values
Stock Code               0
ABC_Class                0
On Hand Qty              0
Avg_Monthly_Sales        0
Stock_Status             0
Suggested_Reorder_Qty    0
Recommendation           0
dtype: int64

4. Negative Reorder Quantity
Products: 0

5. No-Sales Products Incorrectly Reordered
Products: 0

6. Urgent Reorder
Products: 242
Urgent Products With Stock > 0: 0

7. Purchase History Reference
Products With Recent Purchase: 15
Recent Purchase Units: 115

8. Recommendation Total
Recommendation
Reorder                    508
Hold / Monitor             446
Urgent Reorder             242
Review / Do Not Reorder    124
Name: count, dtype: int64

Check Total: 1320

es — Step 5.12 passed the validation checks shown in your output.
The important results are:
Product Master:                    1,320 ✓
Recommendation Table:              1,320 ✓
Duplicate Stock Codes:                 0 ✓
Missing Important Values:              0 ✓
Negative Reorder Quantities:           0 ✓
No-Sales Incorrectly Reordered:        0 ✓
Check Total:                        1,320 ✓
So we can continue.
Step 5.13 — Save Final Purchasing Decision Dataset
This saves the result for your dashboard. It does not change inventory and does not add purchase history to On Hand Qty.

In [55]:
# ==========================================================
# STEP 5.13 — SAVE FINAL PURCHASING DECISION DATASET
# ==========================================================

# ----------------------------------------------------------
# 1. REMOVE INTERNAL SORTING COLUMN
# ----------------------------------------------------------

final_purchase_decision = purchase_recommendation.copy()

if "Priority_Order" in final_purchase_decision.columns:
    final_purchase_decision = final_purchase_decision.drop(
        columns=["Priority_Order"]
    )


# ----------------------------------------------------------
# 2. SAVE FULL DECISION DATASET
# ----------------------------------------------------------

final_purchase_decision.to_csv(
    "ashley_purchasing_decision.csv",
    index=False
)


# ----------------------------------------------------------
# 3. SAVE ONLY PRODUCTS THAT NEED REORDER
# ----------------------------------------------------------

reorder_only = final_purchase_decision[
    final_purchase_decision["Recommendation"].isin(
        ["Urgent Reorder", "Reorder"]
    )
].copy()

reorder_only.to_csv(
    "ashley_reorder_list.csv",
    index=False
)


# ----------------------------------------------------------
# 4. FINAL CHECK
# ----------------------------------------------------------

print("========== FILES SAVED ==========")

print("\n1. ashley_purchasing_decision.csv")
print("Products:", len(final_purchase_decision))

print("\n2. ashley_reorder_list.csv")
print("Products Needing Reorder:", len(reorder_only))

print(
    "Total Suggested Reorder Units:",
    reorder_only["Suggested_Reorder_Qty"].sum()
)

print("\nRecommendation Summary:")

print(
    final_purchase_decision["Recommendation"]
    .value_counts()
)

print("\nIMPORTANT:")
print("Inventory On Hand Qty was NOT changed.")
print("Purchase history remains separate.")

========== FILES SAVED ==========

1. ashley_purchasing_decision.csv
Products: 1320

2. ashley_reorder_list.csv
Products Needing Reorder: 750
Total Suggested Reorder Units: 1234

Recommendation Summary:
Recommendation
Reorder                    508
Hold / Monitor             446
Urgent Reorder             242
Review / Do Not Reorder    124
Name: count, dtype: int64

IMPORTANT:
Inventory On Hand Qty was NOT changed.
Purchase history remains separate.

Data output files 

purchase_history.csv
        ↓
Historical purchase records

ashley_purchasing_decision.csv
        ↓
All 1,320 products + decision information

ashley_reorder_list.csv
        ↓
Only 750 products currently suggested for reorder
Full version of chat gpt 
Main chat-
https://chatgpt.com/share/6aaabd4c-e484-83ec-b785-f7144879cd9f

                                    (Helper explanation
                                    https://chatgpt.com/share/6aaabd6d-ed98-83ec-84ea-775a9e34f246)

Additional explanation 


Purchasing Decision Support System structure-

INPUT DATA
│
├── Sales Data
├── Inventory Data
└── Purchase Data
        ↓
DATA PREPARATION
        ↓
Product Master
        ↓
ANALYSIS
├── ABC Analysis
├── Sales Velocity
├── Current Stock
├── Stock Coverage
└── Purchase History Check
        ↓
DECISION LOGIC
├── Urgent Reorder
├── Reorder
├── Hold / Monitor
└── Review / Do Not Reorder
        ↓
OUTPUT
├── Suggested Reorder Quantity
├── Purchasing Decision Dataset
└── Reorder List
        ↓
MANAGEMENT DECISION

In one sentence:  
The system combines sales + current inventory + purchase history to identify what products need attention, which products should be reordered, and how many units are suggested.

Yes. At this point, you have **3 main output files**, and each has a different purpose.

| File | What it represents | Main use |
|---|---|---|
| `purchase_history.csv` | Historical purchase records | Remember what has already been purchased and prevent duplicate uploads |
| `ashley_purchasing_decision.csv` | **Complete purchasing decision dataset** | Main dataset for the purchasing decision-support dashboard |
| `ashley_reorder_list.csv` | Products that currently need stock | Action list for the purchasing manager |

### 1. `purchase_history.csv` — Purchase History

This stores **what Ashley has purchased before**. Currently, you have **15 purchase records totaling 115 units**.

It contains data such as:

```text
Branch
Date
Stock Code
Description
Quantity
UOM
Buying Price
Location
```

For example:

```text
Ashley | 2026-09-04 | AB596W1 | Ab Walk | 18 | ... | Buying Price | Location
```

Its job is mainly:

**Purchase upload → duplicate check → save history**

Very importantly, this file **does NOT increase `On Hand Qty`**. It is a historical/reference file.

---

### 2. `ashley_purchasing_decision.csv` — Main Decision Dataset ⭐

This is the **most important file for your system**.

It contains **all 1,320 Ashley products**, not just products needing reorder.

It combines information from your analysis:

```text
Stock Code
Description
ABC_Class
Price Range
Selling Price
Buying Price

Total_Qty_Sold
Total_Sales_Value
Avg_Monthly_Sales

On Hand Qty
Stock_Coverage_Months
Stock_Status

Purchasing_Priority
Suggested_Reorder_Qty

Recent_Purchase_Qty
Last_Purchase_Date

Recommendation
Purchase_Note
```

So one row can tell management something like:

```text
Product: F2326
Description: Luofu
ABC: A
Average Monthly Sales: 7.07
On Hand: 0
Coverage: 0 months
Suggested Reorder: 22
Recommendation: Urgent Reorder
```

This file answers:

> **“What should management do with each product?”**

Your current 1,320 products are divided into:

```text
Urgent Reorder             242
Reorder                    508
Hold / Monitor             446
Review / Do Not Reorder    124
                           ----
Total                    1,320
```

This should eventually be the **main source for your Purchasing Decision Support dashboard**.

---

### 3. `ashley_reorder_list.csv` — Purchasing Action List

This is a smaller version of the decision file.

Instead of all 1,320 products, it contains only:

```text
Urgent Reorder
+
Reorder
```

So currently:

```text
Urgent Reorder = 242
Reorder        = 508
                 ---
Total          = 750 products
```

And:

```text
Total Suggested Reorder Units = 1,234
```

It contains essentially the same useful product information, but only for products where:

```text
Suggested_Reorder_Qty > 0
```

This file answers:

> **“Which products should the purchasing manager look at for purchasing now?”**

### How the 3 files work together

```text
                    YOUR SYSTEM

 SALE.CSV ──────────────┐
                        │
 INVENTORY.CSV ─────────┼──→ Analysis
                        │       │
 PURCHASE.CSV ──→ Clean │       │
       │                │       ↓
       ↓                │  ashley_purchasing_decision.csv
 purchase_history.csv   │       │
                        │       ├── All 1,320 products
                        │       │
                        │       ↓
                        └→ ashley_reorder_list.csv
                                │
                                └── 750 products needing reorder
```

The simplest way to remember them is:

**`purchase_history.csv` = What did we purchase?**

**`ashley_purchasing_decision.csv` = What is the situation of every product and what should we do?**

**`ashley_reorder_list.csv` = What products need purchasing attention now?**

And your **inventory remains separate**: `On Hand Qty` comes from inventory; purchase history does not get added to it.